//------------------------------------------------------------------------------
// <auto-generated>
	//     This code was generated from a template.
	//
	//     Manual changes to this file may cause unexpected behavior in your application.
	//     Manual changes to this file will be overwritten if the code is regenerated.
	//
//</auto-generated>
//------------------------------------------------------------------------------
#nullable enable


namespace Cdms.Types.Alvs.Mapping;

public static class CheckMapper
{
	public static Cdms.Model.Alvs.Check Map(Cdms.Types.Alvs.Check from)
	{
	if(from is null)
	{
		return default!;
	}
		var to = new Cdms.Model.Alvs.Check ();
to.CheckCode = from.CheckCode;
            to.DepartmentCode = from.DepartmentCode;
            	return to;
	}
}

