//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable

using JsonApiDotNetCore.Resources.Annotations;
using System.Text.Json.Serialization;
using System.Dynamic;


namespace Cdms.Model.Ipaffs;

/// <summary>
/// Details about the manual inspection override
/// </summary>
public partial class InspectionOverride  //
{


        /// <summary>
        /// Original inspection decision
        /// </summary>
    [Attr]
    [System.ComponentModel.Description("Original inspection decision")]
    public string? OriginalDecision { get; set; }

	
        /// <summary>
        /// The time the risk decision is overridden
        /// </summary>
    [Attr]
    [System.ComponentModel.Description("The time the risk decision is overridden")]
    public DateTime? OverriddenOn { get; set; }

	
        /// <summary>
        /// User entity who has manually overridden the inspection
        /// </summary>
    [Attr]
    [System.ComponentModel.Description("User entity who has manually overridden the inspection")]
    public UserInformation? OverriddenBy { get; set; }

	}


