//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable

using JsonApiDotNetCore.Resources.Annotations;
using System.Text.Json.Serialization;
using System.Dynamic;


namespace Cdms.Model.Ipaffs;

/// <summary>
/// Part 1 - Holds the information related to veterinary checks and details
/// </summary>
public partial class VeterinaryInformation  //
{


        /// <summary>
        /// External reference of approved establishments, which relates to a downstream service
        /// </summary>
    [Attr]
    [System.ComponentModel.Description("External reference of approved establishments, which relates to a downstream service")]
    public ExternalReference? EstablishmentsOfOriginExternalReference { get; set; }

	
        /// <summary>
        /// List of establishments which were approved by UK to issue veterinary documents
        /// </summary>
    [Attr]
    [System.ComponentModel.Description("List of establishments which were approved by UK to issue veterinary documents")]
    public ApprovedEstablishment[]? EstablishmentsOfOrigins { get; set; }

	
        /// <summary>
        /// Veterinary document identification
        /// </summary>
    [Attr]
    [System.ComponentModel.Description("Veterinary document identification")]
    public string? VeterinaryDocument { get; set; }

	
        /// <summary>
        /// Veterinary document issue date
        /// </summary>
    [Attr]
    [System.ComponentModel.Description("Veterinary document issue date")]
    public DateOnly? VeterinaryDocumentIssuedOn { get; set; }

	
        /// <summary>
        /// Additional documents
        /// </summary>
    [Attr]
    [System.ComponentModel.Description("Additional documents")]
    public string[]? AccompanyingDocumentNumbers { get; set; }

	
        /// <summary>
        /// Accompanying documents
        /// </summary>
    [Attr]
    [System.ComponentModel.Description("Accompanying documents")]
    public AccompanyingDocument[]? AccompanyingDocuments { get; set; }

	
        /// <summary>
        /// Catch certificate attachments
        /// </summary>
    [Attr]
    [System.ComponentModel.Description("Catch certificate attachments")]
    public CatchCertificateAttachment[]? CatchCertificateAttachments { get; set; }

	
        /// <summary>
        /// Details helpful for identification
        /// </summary>
    [Attr]
    [System.ComponentModel.Description("Details helpful for identification")]
    public IdentificationDetails[]? IdentificationDetails { get; set; }

	}


