//------------------------------------------------------------------------------
// <auto-generated>
	//     This code was generated from a template.
	//
	//     Manual changes to this file may cause unexpected behavior in your application.
	//     Manual changes to this file will be overwritten if the code is regenerated.
	//
//</auto-generated>
//------------------------------------------------------------------------------
#nullable enable


namespace Cdms.Types.Gmr.Mapping;

public static class SearchGmrsForVRNsresponseMapper
{
	public static Cdms.Model.VehicleMovement.SearchGmrsForVRNsresponse Map(Cdms.Types.Gmr.SearchGmrsForVRNsresponse from)
	{
	if(from is null)
	{
		return default!;
	}
		var to = new Cdms.Model.VehicleMovement.SearchGmrsForVRNsresponse ();
to.GmrsByVRNs = from?.GmrsByVRNs?.Select(x => GmrsByVRNMapper.Map(x)).ToArray();
                to.Gmrs = from?.Gmrs?.Select(x => GmrMapper.Map(x)).ToArray();
                	return to;
	}
}

