//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable

using System.Text.Json.Serialization;
using System.Dynamic;


namespace Cdms.Types.Ipaffs;

/// <summary>
/// Party details
/// </summary>
public partial class Party  //
{


        /// <summary>
        /// IPAFFS ID of party
        /// </summary>
    [JsonPropertyName("id")]
    public string? Id { get; set; }

	
        /// <summary>
        /// Name of party
        /// </summary>
    [JsonPropertyName("name")]
    [Cdms.SensitiveData.SensitiveData]
    public string? Name { get; set; }

	
        /// <summary>
        /// Company ID
        /// </summary>
    [JsonPropertyName("companyId")]
    public string? CompanyId { get; set; }

	
        /// <summary>
        /// Contact ID (B2C)
        /// </summary>
    [JsonPropertyName("contactId")]
    public string? ContactId { get; set; }

	
        /// <summary>
        /// Company name
        /// </summary>
    [JsonPropertyName("companyName")]
    [Cdms.SensitiveData.SensitiveData]
    public string? CompanyName { get; set; }

	
        /// <summary>
        /// Addresses
        /// </summary>
    [JsonPropertyName("address")]
    [Cdms.SensitiveData.SensitiveData]
    public string[]? Addresses { get; set; }

	
        /// <summary>
        /// County
        /// </summary>
    [JsonPropertyName("county")]
    public string? County { get; set; }

	
        /// <summary>
        /// Post code of party
        /// </summary>
    [JsonPropertyName("postCode")]
    [Cdms.SensitiveData.SensitiveData]
    public string? PostCode { get; set; }

	
        /// <summary>
        /// Country of party
        /// </summary>
    [JsonPropertyName("country")]
    public string? Country { get; set; }

	
        /// <summary>
        /// City
        /// </summary>
    [JsonPropertyName("city")]
    [Cdms.SensitiveData.SensitiveData]
    public string? City { get; set; }

	
        /// <summary>
        /// TRACES ID
        /// </summary>
    [JsonPropertyName("tracesID")]
    public int? TracesId { get; set; }

	
        /// <summary>
        /// Type of party
        /// </summary>
    [JsonPropertyName("type")]
    public PartyTypeEnum? Type { get; set; }

	
        /// <summary>
        /// Approval number
        /// </summary>
    [JsonPropertyName("approvalNumber")]
    public string? ApprovalNumber { get; set; }

	
        /// <summary>
        /// Phone number of party
        /// </summary>
    [JsonPropertyName("phone")]
    [Cdms.SensitiveData.SensitiveData]
    public string? Phone { get; set; }

	
        /// <summary>
        /// Fax number of party
        /// </summary>
    [JsonPropertyName("fax")]
    [Cdms.SensitiveData.SensitiveData]
    public string? Fax { get; set; }

	
        /// <summary>
        /// Email number of party
        /// </summary>
    [JsonPropertyName("email")]
    [Cdms.SensitiveData.SensitiveData]
    public string? Email { get; set; }

	}


