//------------------------------------------------------------------------------
// <auto-generated>
	//     This code was generated from a template.
	//
	//     Manual changes to this file may cause unexpected behavior in your application.
	//     Manual changes to this file will be overwritten if the code is regenerated.
	//
//</auto-generated>
//------------------------------------------------------------------------------
#nullable enable


namespace Cdms.Types.Gvms.Mapping;

public static class DeclarationsMapper
{
	public static Cdms.Model.Gvms.Declarations Map(Cdms.Types.Gvms.Declarations from)
	{
	if(from is null)
	{
		return default!;
	}
		var to = new Cdms.Model.Gvms.Declarations ();
to.Transits = from?.Transits?.Select(x => TransitsMapper.Map(x)).ToArray();
                to.Customs = from?.Customs?.Select(x => CustomsMapper.Map(x)).ToArray();
                	return to;
	}
}

