//------------------------------------------------------------------------------
// <auto-generated>
    //     This code was generated from a template.
    //
    //     Manual changes to this file may cause unexpected behavior in your application.
    //     Manual changes to this file will be overwritten if the code is regenerated.
    // </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Cdms.Types.Gmr.Mapping;

public static class DirectionEnumMapper
{
public static Cdms.Model.VehicleMovement.DirectionEnum? Map(Cdms.Types.Gmr.DirectionEnum? from)
{
if(from == null)
{
return default!;
}
return from switch
{
Cdms.Types.Gmr.DirectionEnum.UkInbound => Cdms.Model.VehicleMovement.DirectionEnum.UkInbound,
    Cdms.Types.Gmr.DirectionEnum.UkOutbound => Cdms.Model.VehicleMovement.DirectionEnum.UkOutbound,
    Cdms.Types.Gmr.DirectionEnum.GbToNi => Cdms.Model.VehicleMovement.DirectionEnum.GbToNi,
    Cdms.Types.Gmr.DirectionEnum.NiToGb => Cdms.Model.VehicleMovement.DirectionEnum.NiToGb,
     
};
}
        

}


