//------------------------------------------------------------------------------
// <auto-generated>
	//     This code was generated from a template.
	//
	//     Manual changes to this file may cause unexpected behavior in your application.
	//     Manual changes to this file will be overwritten if the code is regenerated.
	//
//</auto-generated>
//------------------------------------------------------------------------------
#nullable enable


namespace Cdms.Types.Gmr.Mapping;

public static class ErrorResponseMapper
{
	public static Cdms.Model.VehicleMovement.ErrorResponse Map(Cdms.Types.Gmr.ErrorResponse from)
	{
	if(from is null)
	{
		return default!;
	}
		var to = new Cdms.Model.VehicleMovement.ErrorResponse ();
to.Code = from.Code;
            	return to;
	}
}

