//------------------------------------------------------------------------------
// <auto-generated>
	//     This code was generated from a template.
	//
	//     Manual changes to this file may cause unexpected behavior in your application.
	//     Manual changes to this file will be overwritten if the code is regenerated.
	//
//</auto-generated>
//------------------------------------------------------------------------------
#nullable enable


namespace Cdms.Types.Gvms.Mapping;

public static class GmrByDeclarationIdMapper
{
	public static Cdms.Model.Gvms.GmrByDeclarationId Map(Cdms.Types.Gvms.GmrByDeclarationId from)
	{
	if(from is null)
	{
		return default!;
	}
		var to = new Cdms.Model.Gvms.GmrByDeclarationId ();
to.Dec = from.Dec;
            	return to;
	}
}

