//------------------------------------------------------------------------------
// <auto-generated>
	//     This code was generated from a template.
	//
	//     Manual changes to this file may cause unexpected behavior in your application.
	//     Manual changes to this file will be overwritten if the code is regenerated.
	//
//</auto-generated>
//------------------------------------------------------------------------------
#nullable enable


namespace Cdms.Types.Gvms.Mapping;

public static class GmrsByVrnMapper
{
	public static Cdms.Model.Gvms.GmrsByVrn Map(Cdms.Types.Gvms.GmrsByVrn from)
	{
	if(from is null)
	{
		return default!;
	}
		var to = new Cdms.Model.Gvms.GmrsByVrn ();
to.Vrn = from.Vrn;
            	return to;
	}
}

