//------------------------------------------------------------------------------
// <auto-generated>
	//     This code was generated from a template.
	//
	//     Manual changes to this file may cause unexpected behavior in your application.
	//     Manual changes to this file will be overwritten if the code is regenerated.
	//
//</auto-generated>
//------------------------------------------------------------------------------
#nullable enable


namespace Cdms.Types.Gmr.Mapping;

public static class SearchGmrsForVRNrequestMapper
{
	public static Cdms.Model.VehicleMovement.SearchGmrsForVRNrequest Map(Cdms.Types.Gmr.SearchGmrsForVRNrequest from)
	{
	if(from is null)
	{
		return default!;
	}
		var to = new Cdms.Model.VehicleMovement.SearchGmrsForVRNrequest ();
	return to;
	}
}

