//------------------------------------------------------------------------------
// <auto-generated>
    //     This code was generated from a template.
    //
    //     Manual changes to this file may cause unexpected behavior in your application.
    //     Manual changes to this file will be overwritten if the code is regenerated.
    // </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Cdms.Types.Gmr.Mapping;

public static class StateEnumMapper
{
public static Cdms.Model.VehicleMovement.StateEnum? Map(Cdms.Types.Gmr.StateEnum? from)
{
if(from == null)
{
return default!;
}
return from switch
{
Cdms.Types.Gmr.StateEnum.NotFinalisable => Cdms.Model.VehicleMovement.StateEnum.NotFinalisable,
    Cdms.Types.Gmr.StateEnum.Open => Cdms.Model.VehicleMovement.StateEnum.Open,
    Cdms.Types.Gmr.StateEnum.Finalised => Cdms.Model.VehicleMovement.StateEnum.Finalised,
    Cdms.Types.Gmr.StateEnum.CheckedIn => Cdms.Model.VehicleMovement.StateEnum.CheckedIn,
    Cdms.Types.Gmr.StateEnum.Embarked => Cdms.Model.VehicleMovement.StateEnum.Embarked,
    Cdms.Types.Gmr.StateEnum.Completed => Cdms.Model.VehicleMovement.StateEnum.Completed,
     
};
}
        

}


