//------------------------------------------------------------------------------
// <auto-generated>
	//     This code was generated from a template.
	//
	//     Manual changes to this file may cause unexpected behavior in your application.
	//     Manual changes to this file will be overwritten if the code is regenerated.
	//
//</auto-generated>
//------------------------------------------------------------------------------
#nullable enable


namespace Cdms.Types.Ipaffs.Mapping;

public static class AccompanyingDocumentMapper
{
	public static Cdms.Model.Ipaffs.AccompanyingDocument Map(Cdms.Types.Ipaffs.AccompanyingDocument from)
	{
	if(from is null)
	{
		return default!;
	}
		var to = new Cdms.Model.Ipaffs.AccompanyingDocument ();
to.DocumentType = AccompanyingDocumentDocumentTypeEnumMapper.Map(from?.DocumentType);
                to.DocumentReference = from.DocumentReference;
            to.DocumentIssuedOn = from.DocumentIssueDate;
            to.AttachmentId = from.AttachmentId;
            to.AttachmentFilename = from.AttachmentFilename;
            to.AttachmentContentType = from.AttachmentContentType;
            to.UploadUserId = from.UploadUserId;
            to.UploadOrganisationId = from.UploadOrganisationId;
            to.ExternalReference = ExternalReferenceMapper.Map(from?.ExternalReference);
                	return to;
	}
}

