//------------------------------------------------------------------------------
// <auto-generated>
    //     This code was generated from a template.
    //
    //     Manual changes to this file may cause unexpected behavior in your application.
    //     Manual changes to this file will be overwritten if the code is regenerated.
    // </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Cdms.Types.Ipaffs.Mapping;

public static class AccompanyingDocumentDocumentTypeEnumMapper
{
    public static Cdms.Model.Ipaffs.AccompanyingDocumentDocumentTypeEnum? Map(
        Cdms.Types.Ipaffs.AccompanyingDocumentDocumentTypeEnum? from)
    {
        if (from == null)
        {
            return default!;
        }

        return from switch
        {
            Cdms.Types.Ipaffs.AccompanyingDocumentDocumentTypeEnum.AirWaybill => Cdms.Model.Ipaffs
                .AccompanyingDocumentDocumentTypeEnum.AirWaybill,
            Cdms.Types.Ipaffs.AccompanyingDocumentDocumentTypeEnum.BillOfLading => Cdms.Model.Ipaffs
                .AccompanyingDocumentDocumentTypeEnum.BillOfLading,
            Cdms.Types.Ipaffs.AccompanyingDocumentDocumentTypeEnum.CargoManifest => Cdms.Model.Ipaffs
                .AccompanyingDocumentDocumentTypeEnum.CargoManifest,
            Cdms.Types.Ipaffs.AccompanyingDocumentDocumentTypeEnum.CatchCertificate => Cdms.Model.Ipaffs
                .AccompanyingDocumentDocumentTypeEnum.CatchCertificate,
            Cdms.Types.Ipaffs.AccompanyingDocumentDocumentTypeEnum.CommercialDocument => Cdms.Model.Ipaffs
                .AccompanyingDocumentDocumentTypeEnum.CommercialDocument,
            Cdms.Types.Ipaffs.AccompanyingDocumentDocumentTypeEnum.CommercialInvoice => Cdms.Model.Ipaffs
                .AccompanyingDocumentDocumentTypeEnum.CommercialInvoice,
            Cdms.Types.Ipaffs.AccompanyingDocumentDocumentTypeEnum.ConformityCertificate => Cdms.Model.Ipaffs
                .AccompanyingDocumentDocumentTypeEnum.ConformityCertificate,
            Cdms.Types.Ipaffs.AccompanyingDocumentDocumentTypeEnum.ContainerManifest => Cdms.Model.Ipaffs
                .AccompanyingDocumentDocumentTypeEnum.ContainerManifest,
            Cdms.Types.Ipaffs.AccompanyingDocumentDocumentTypeEnum.CustomsDeclaration => Cdms.Model.Ipaffs
                .AccompanyingDocumentDocumentTypeEnum.CustomsDeclaration,
            Cdms.Types.Ipaffs.AccompanyingDocumentDocumentTypeEnum.Docom => Cdms.Model.Ipaffs
                .AccompanyingDocumentDocumentTypeEnum.Docom,
            Cdms.Types.Ipaffs.AccompanyingDocumentDocumentTypeEnum.HealthCertificate => Cdms.Model.Ipaffs
                .AccompanyingDocumentDocumentTypeEnum.HealthCertificate,
            Cdms.Types.Ipaffs.AccompanyingDocumentDocumentTypeEnum.HeatTreatmentCertificate => Cdms.Model.Ipaffs
                .AccompanyingDocumentDocumentTypeEnum.HeatTreatmentCertificate,
            Cdms.Types.Ipaffs.AccompanyingDocumentDocumentTypeEnum.ImportPermit => Cdms.Model.Ipaffs
                .AccompanyingDocumentDocumentTypeEnum.ImportPermit,
            Cdms.Types.Ipaffs.AccompanyingDocumentDocumentTypeEnum.InspectionCertificate => Cdms.Model.Ipaffs
                .AccompanyingDocumentDocumentTypeEnum.InspectionCertificate,
            Cdms.Types.Ipaffs.AccompanyingDocumentDocumentTypeEnum.Itahc => Cdms.Model.Ipaffs
                .AccompanyingDocumentDocumentTypeEnum.Itahc,
            Cdms.Types.Ipaffs.AccompanyingDocumentDocumentTypeEnum.JourneyLog => Cdms.Model.Ipaffs
                .AccompanyingDocumentDocumentTypeEnum.JourneyLog,
            Cdms.Types.Ipaffs.AccompanyingDocumentDocumentTypeEnum.LaboratorySamplingResultsForAflatoxin => Cdms.Model
                .Ipaffs.AccompanyingDocumentDocumentTypeEnum.LaboratorySamplingResultsForAflatoxin,
            Cdms.Types.Ipaffs.AccompanyingDocumentDocumentTypeEnum.LatestVeterinaryHealthCertificate => Cdms.Model
                .Ipaffs.AccompanyingDocumentDocumentTypeEnum.LatestVeterinaryHealthCertificate,
            Cdms.Types.Ipaffs.AccompanyingDocumentDocumentTypeEnum.LetterOfAuthority => Cdms.Model.Ipaffs
                .AccompanyingDocumentDocumentTypeEnum.LetterOfAuthority,
            Cdms.Types.Ipaffs.AccompanyingDocumentDocumentTypeEnum.LicenseOrAuthorisation => Cdms.Model.Ipaffs
                .AccompanyingDocumentDocumentTypeEnum.LicenseOrAuthorisation,
            Cdms.Types.Ipaffs.AccompanyingDocumentDocumentTypeEnum.MycotoxinCertification => Cdms.Model.Ipaffs
                .AccompanyingDocumentDocumentTypeEnum.MycotoxinCertification,
            Cdms.Types.Ipaffs.AccompanyingDocumentDocumentTypeEnum.OriginCertificate => Cdms.Model.Ipaffs
                .AccompanyingDocumentDocumentTypeEnum.OriginCertificate,
            Cdms.Types.Ipaffs.AccompanyingDocumentDocumentTypeEnum.Other => Cdms.Model.Ipaffs
                .AccompanyingDocumentDocumentTypeEnum.Other,
            Cdms.Types.Ipaffs.AccompanyingDocumentDocumentTypeEnum.PhytosanitaryCertificate => Cdms.Model.Ipaffs
                .AccompanyingDocumentDocumentTypeEnum.PhytosanitaryCertificate,
            Cdms.Types.Ipaffs.AccompanyingDocumentDocumentTypeEnum.ProcessingStatement => Cdms.Model.Ipaffs
                .AccompanyingDocumentDocumentTypeEnum.ProcessingStatement,
            Cdms.Types.Ipaffs.AccompanyingDocumentDocumentTypeEnum.ProofOfStorage => Cdms.Model.Ipaffs
                .AccompanyingDocumentDocumentTypeEnum.ProofOfStorage,
            Cdms.Types.Ipaffs.AccompanyingDocumentDocumentTypeEnum.RailwayBill => Cdms.Model.Ipaffs
                .AccompanyingDocumentDocumentTypeEnum.RailwayBill,
            Cdms.Types.Ipaffs.AccompanyingDocumentDocumentTypeEnum.SeaWaybill => Cdms.Model.Ipaffs
                .AccompanyingDocumentDocumentTypeEnum.SeaWaybill,
            Cdms.Types.Ipaffs.AccompanyingDocumentDocumentTypeEnum.VeterinaryHealthCertificate => Cdms.Model.Ipaffs
                .AccompanyingDocumentDocumentTypeEnum.VeterinaryHealthCertificate,
            Cdms.Types.Ipaffs.AccompanyingDocumentDocumentTypeEnum.ListOfIngredients => Cdms.Model.Ipaffs
                .AccompanyingDocumentDocumentTypeEnum.ListOfIngredients,
            Cdms.Types.Ipaffs.AccompanyingDocumentDocumentTypeEnum.PackingList => Cdms.Model.Ipaffs
                .AccompanyingDocumentDocumentTypeEnum.PackingList,
            Cdms.Types.Ipaffs.AccompanyingDocumentDocumentTypeEnum.RoadConsignmentNote => Cdms.Model.Ipaffs
                .AccompanyingDocumentDocumentTypeEnum.RoadConsignmentNote,

            _ => throw new ArgumentOutOfRangeException(nameof(from), from, null)
        };
    }


}


