//------------------------------------------------------------------------------
// <auto-generated>
    //     This code was generated from a template.
    //
    //     Manual changes to this file may cause unexpected behavior in your application.
    //     Manual changes to this file will be overwritten if the code is regenerated.
    // </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Cdms.Types.Ipaffs.Mapping;

public static class AnimalCertificationEnumMapper
{
public static Cdms.Model.Ipaffs.AnimalCertificationEnum? Map(Cdms.Types.Ipaffs.AnimalCertificationEnum? from)
{
if(from == null)
{
return default!;
}
return from switch
{
Cdms.Types.Ipaffs.AnimalCertificationEnum.AnimalFeedingStuff => Cdms.Model.Ipaffs.AnimalCertificationEnum.AnimalFeedingStuff,
    Cdms.Types.Ipaffs.AnimalCertificationEnum.Approved => Cdms.Model.Ipaffs.AnimalCertificationEnum.Approved,
    Cdms.Types.Ipaffs.AnimalCertificationEnum.ArtificialReproduction => Cdms.Model.Ipaffs.AnimalCertificationEnum.ArtificialReproduction,
    Cdms.Types.Ipaffs.AnimalCertificationEnum.Breeding => Cdms.Model.Ipaffs.AnimalCertificationEnum.Breeding,
    Cdms.Types.Ipaffs.AnimalCertificationEnum.Circus => Cdms.Model.Ipaffs.AnimalCertificationEnum.Circus,
    Cdms.Types.Ipaffs.AnimalCertificationEnum.CommercialSale => Cdms.Model.Ipaffs.AnimalCertificationEnum.CommercialSale,
    Cdms.Types.Ipaffs.AnimalCertificationEnum.CommercialSaleOrChangeOfOwnership => Cdms.Model.Ipaffs.AnimalCertificationEnum.CommercialSaleOrChangeOfOwnership,
    Cdms.Types.Ipaffs.AnimalCertificationEnum.Fattening => Cdms.Model.Ipaffs.AnimalCertificationEnum.Fattening,
    Cdms.Types.Ipaffs.AnimalCertificationEnum.GameRestocking => Cdms.Model.Ipaffs.AnimalCertificationEnum.GameRestocking,
    Cdms.Types.Ipaffs.AnimalCertificationEnum.HumanConsumption => Cdms.Model.Ipaffs.AnimalCertificationEnum.HumanConsumption,
    Cdms.Types.Ipaffs.AnimalCertificationEnum.InternalMarket => Cdms.Model.Ipaffs.AnimalCertificationEnum.InternalMarket,
    Cdms.Types.Ipaffs.AnimalCertificationEnum.Other => Cdms.Model.Ipaffs.AnimalCertificationEnum.Other,
    Cdms.Types.Ipaffs.AnimalCertificationEnum.PersonallyOwnedPetsNotForRehoming => Cdms.Model.Ipaffs.AnimalCertificationEnum.PersonallyOwnedPetsNotForRehoming,
    Cdms.Types.Ipaffs.AnimalCertificationEnum.Pets => Cdms.Model.Ipaffs.AnimalCertificationEnum.Pets,
    Cdms.Types.Ipaffs.AnimalCertificationEnum.Production => Cdms.Model.Ipaffs.AnimalCertificationEnum.Production,
    Cdms.Types.Ipaffs.AnimalCertificationEnum.Quarantine => Cdms.Model.Ipaffs.AnimalCertificationEnum.Quarantine,
    Cdms.Types.Ipaffs.AnimalCertificationEnum.RacingCompetition => Cdms.Model.Ipaffs.AnimalCertificationEnum.RacingCompetition,
    Cdms.Types.Ipaffs.AnimalCertificationEnum.RegisteredEquidae => Cdms.Model.Ipaffs.AnimalCertificationEnum.RegisteredEquidae,
    Cdms.Types.Ipaffs.AnimalCertificationEnum.Registered => Cdms.Model.Ipaffs.AnimalCertificationEnum.Registered,
    Cdms.Types.Ipaffs.AnimalCertificationEnum.RejectedOrReturnedConsignment => Cdms.Model.Ipaffs.AnimalCertificationEnum.RejectedOrReturnedConsignment,
    Cdms.Types.Ipaffs.AnimalCertificationEnum.Relaying => Cdms.Model.Ipaffs.AnimalCertificationEnum.Relaying,
    Cdms.Types.Ipaffs.AnimalCertificationEnum.RescueRehoming => Cdms.Model.Ipaffs.AnimalCertificationEnum.RescueRehoming,
    Cdms.Types.Ipaffs.AnimalCertificationEnum.Research => Cdms.Model.Ipaffs.AnimalCertificationEnum.Research,
    Cdms.Types.Ipaffs.AnimalCertificationEnum.Slaughter => Cdms.Model.Ipaffs.AnimalCertificationEnum.Slaughter,
    Cdms.Types.Ipaffs.AnimalCertificationEnum.TechnicalPharmaceuticalUse => Cdms.Model.Ipaffs.AnimalCertificationEnum.TechnicalPharmaceuticalUse,
    Cdms.Types.Ipaffs.AnimalCertificationEnum.Transit => Cdms.Model.Ipaffs.AnimalCertificationEnum.Transit,
    Cdms.Types.Ipaffs.AnimalCertificationEnum.ZooCollection => Cdms.Model.Ipaffs.AnimalCertificationEnum.ZooCollection,

    _ => throw new ArgumentOutOfRangeException(nameof(from), from, null)
};
}
        

}


