//------------------------------------------------------------------------------
// <auto-generated>
    //     This code was generated from a template.
    //
    //     Manual changes to this file may cause unexpected behavior in your application.
    //     Manual changes to this file will be overwritten if the code is regenerated.
    // </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Cdms.Types.Ipaffs.Mapping;

public static class ApplicantAnalysisTypeEnumMapper
{
public static Cdms.Model.Ipaffs.ApplicantAnalysisTypeEnum? Map(Cdms.Types.Ipaffs.ApplicantAnalysisTypeEnum? from)
{
if(from == null)
{
return default!;
}
return from switch
{
Cdms.Types.Ipaffs.ApplicantAnalysisTypeEnum.InitialAnalysis => Cdms.Model.Ipaffs.ApplicantAnalysisTypeEnum.InitialAnalysis,
    Cdms.Types.Ipaffs.ApplicantAnalysisTypeEnum.CounterAnalysis => Cdms.Model.Ipaffs.ApplicantAnalysisTypeEnum.CounterAnalysis,
    Cdms.Types.Ipaffs.ApplicantAnalysisTypeEnum.SecondExpertAnalysis => Cdms.Model.Ipaffs.ApplicantAnalysisTypeEnum.SecondExpertAnalysis,
     
};
}
        

}


