//------------------------------------------------------------------------------
// <auto-generated>
    //     This code was generated from a template.
    //
    //     Manual changes to this file may cause unexpected behavior in your application.
    //     Manual changes to this file will be overwritten if the code is regenerated.
    // </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Cdms.Types.Ipaffs.Mapping;

public static class ApplicantConservationOfSampleEnumMapper
{
public static Cdms.Model.Ipaffs.ApplicantConservationOfSampleEnum? Map(Cdms.Types.Ipaffs.ApplicantConservationOfSampleEnum? from)
{
if(from == null)
{
return default!;
}
return from switch
{
Cdms.Types.Ipaffs.ApplicantConservationOfSampleEnum.Ambient => Cdms.Model.Ipaffs.ApplicantConservationOfSampleEnum.Ambient,
    Cdms.Types.Ipaffs.ApplicantConservationOfSampleEnum.Chilled => Cdms.Model.Ipaffs.ApplicantConservationOfSampleEnum.Chilled,
    Cdms.Types.Ipaffs.ApplicantConservationOfSampleEnum.Frozen => Cdms.Model.Ipaffs.ApplicantConservationOfSampleEnum.Frozen,
     
};
}
        

}


