//------------------------------------------------------------------------------
// <auto-generated>
	//     This code was generated from a template.
	//
	//     Manual changes to this file may cause unexpected behavior in your application.
	//     Manual changes to this file will be overwritten if the code is regenerated.
	//
//</auto-generated>
//------------------------------------------------------------------------------
#nullable enable


namespace Cdms.Types.Ipaffs.Mapping;

public static class ApplicantMapper
{
    public static Cdms.Model.Ipaffs.Applicant Map(Cdms.Types.Ipaffs.Applicant from)
    {
        if (from is null)
        {
            return default!;
        }

        var to = new Cdms.Model.Ipaffs.Applicant();
        to.Laboratory = from?.Laboratory;
        to.LaboratoryAddress = from?.LaboratoryAddress;
        to.LaboratoryIdentification = from?.LaboratoryIdentification;
        to.LaboratoryPhoneNumber = from?.LaboratoryPhoneNumber;
        to.LaboratoryEmail = from?.LaboratoryEmail;
        to.SampleBatchNumber = from?.SampleBatchNumber;
        to.AnalysisType = ApplicantAnalysisTypeEnumMapper.Map(from?.AnalysisType);
        to.NumberOfSamples = from?.NumberOfSamples;
        to.SampleType = from?.SampleType;
        to.ConservationOfSample = ApplicantConservationOfSampleEnumMapper.Map(from?.ConservationOfSample);
        to.Inspector = InspectorMapper.Map(from?.Inspector!);
        to.SampledOn = DateTimeMapper.Map(from?.SampleDate, from?.SampleTime);
        return to;
    }
}

