//------------------------------------------------------------------------------
// <auto-generated>
	//     This code was generated from a template.
	//
	//     Manual changes to this file may cause unexpected behavior in your application.
	//     Manual changes to this file will be overwritten if the code is regenerated.
	//
//</auto-generated>
//------------------------------------------------------------------------------
#nullable enable


namespace Cdms.Types.Ipaffs.Mapping;

public static class CatchCertificatesMapper
{
	public static Cdms.Model.Ipaffs.CatchCertificates Map(Cdms.Types.Ipaffs.CatchCertificates from)
	{
	if(from is null)
	{
		return default!;
	}
		var to = new Cdms.Model.Ipaffs.CatchCertificates ();
to.CertificateNumber = from?.CertificateNumber;
            to.Weight = from?.Weight;
            	return to;
	}
}

