//------------------------------------------------------------------------------
// <auto-generated>
    //     This code was generated from a template.
    //
    //     Manual changes to this file may cause unexpected behavior in your application.
    //     Manual changes to this file will be overwritten if the code is regenerated.
    // </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Cdms.Types.Ipaffs.Mapping;

public static class ChedppNotAcceptableReasonCommodityOrPackageEnumMapper
{
public static Cdms.Model.Ipaffs.ChedppNotAcceptableReasonCommodityOrPackageEnum? Map(Cdms.Types.Ipaffs.ChedppNotAcceptableReasonCommodityOrPackageEnum? from)
{
if(from == null)
{
return default!;
}
return from switch
{
Cdms.Types.Ipaffs.ChedppNotAcceptableReasonCommodityOrPackageEnum.C => Cdms.Model.Ipaffs.ChedppNotAcceptableReasonCommodityOrPackageEnum.C,
    Cdms.Types.Ipaffs.ChedppNotAcceptableReasonCommodityOrPackageEnum.P => Cdms.Model.Ipaffs.ChedppNotAcceptableReasonCommodityOrPackageEnum.P,
    Cdms.Types.Ipaffs.ChedppNotAcceptableReasonCommodityOrPackageEnum.Cp => Cdms.Model.Ipaffs.ChedppNotAcceptableReasonCommodityOrPackageEnum.Cp,

    _ => throw new ArgumentOutOfRangeException(nameof(from), from, null)
};
}
        

}


