//------------------------------------------------------------------------------
// <auto-generated>
    //     This code was generated from a template.
    //
    //     Manual changes to this file may cause unexpected behavior in your application.
    //     Manual changes to this file will be overwritten if the code is regenerated.
    // </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Cdms.Types.Ipaffs.Mapping;

public static class ChedppNotAcceptableReasonReasonEnumMapper
{
public static Cdms.Model.Ipaffs.ChedppNotAcceptableReasonReasonEnum? Map(Cdms.Types.Ipaffs.ChedppNotAcceptableReasonReasonEnum? from)
{
if(from == null)
{
return default!;
}
return from switch
{
Cdms.Types.Ipaffs.ChedppNotAcceptableReasonReasonEnum.DocPhmdm => Cdms.Model.Ipaffs.ChedppNotAcceptableReasonReasonEnum.DocPhmdm,
    Cdms.Types.Ipaffs.ChedppNotAcceptableReasonReasonEnum.DocPhmdii => Cdms.Model.Ipaffs.ChedppNotAcceptableReasonReasonEnum.DocPhmdii,
    Cdms.Types.Ipaffs.ChedppNotAcceptableReasonReasonEnum.DocPa => Cdms.Model.Ipaffs.ChedppNotAcceptableReasonReasonEnum.DocPa,
    Cdms.Types.Ipaffs.ChedppNotAcceptableReasonReasonEnum.DocPic => Cdms.Model.Ipaffs.ChedppNotAcceptableReasonReasonEnum.DocPic,
    Cdms.Types.Ipaffs.ChedppNotAcceptableReasonReasonEnum.DocPill => Cdms.Model.Ipaffs.ChedppNotAcceptableReasonReasonEnum.DocPill,
    Cdms.Types.Ipaffs.ChedppNotAcceptableReasonReasonEnum.DocPed => Cdms.Model.Ipaffs.ChedppNotAcceptableReasonReasonEnum.DocPed,
    Cdms.Types.Ipaffs.ChedppNotAcceptableReasonReasonEnum.DocPmod => Cdms.Model.Ipaffs.ChedppNotAcceptableReasonReasonEnum.DocPmod,
    Cdms.Types.Ipaffs.ChedppNotAcceptableReasonReasonEnum.DocPfi => Cdms.Model.Ipaffs.ChedppNotAcceptableReasonReasonEnum.DocPfi,
    Cdms.Types.Ipaffs.ChedppNotAcceptableReasonReasonEnum.DocPnol => Cdms.Model.Ipaffs.ChedppNotAcceptableReasonReasonEnum.DocPnol,
    Cdms.Types.Ipaffs.ChedppNotAcceptableReasonReasonEnum.DocPcne => Cdms.Model.Ipaffs.ChedppNotAcceptableReasonReasonEnum.DocPcne,
    Cdms.Types.Ipaffs.ChedppNotAcceptableReasonReasonEnum.DocPadm => Cdms.Model.Ipaffs.ChedppNotAcceptableReasonReasonEnum.DocPadm,
    Cdms.Types.Ipaffs.ChedppNotAcceptableReasonReasonEnum.DocPadi => Cdms.Model.Ipaffs.ChedppNotAcceptableReasonReasonEnum.DocPadi,
    Cdms.Types.Ipaffs.ChedppNotAcceptableReasonReasonEnum.DocPpni => Cdms.Model.Ipaffs.ChedppNotAcceptableReasonReasonEnum.DocPpni,
    Cdms.Types.Ipaffs.ChedppNotAcceptableReasonReasonEnum.DocPf => Cdms.Model.Ipaffs.ChedppNotAcceptableReasonReasonEnum.DocPf,
    Cdms.Types.Ipaffs.ChedppNotAcceptableReasonReasonEnum.DocPo => Cdms.Model.Ipaffs.ChedppNotAcceptableReasonReasonEnum.DocPo,
    Cdms.Types.Ipaffs.ChedppNotAcceptableReasonReasonEnum.DocNcevd => Cdms.Model.Ipaffs.ChedppNotAcceptableReasonReasonEnum.DocNcevd,
    Cdms.Types.Ipaffs.ChedppNotAcceptableReasonReasonEnum.DocNcpqefi => Cdms.Model.Ipaffs.ChedppNotAcceptableReasonReasonEnum.DocNcpqefi,
    Cdms.Types.Ipaffs.ChedppNotAcceptableReasonReasonEnum.DocNcpqebec => Cdms.Model.Ipaffs.ChedppNotAcceptableReasonReasonEnum.DocNcpqebec,
    Cdms.Types.Ipaffs.ChedppNotAcceptableReasonReasonEnum.DocNcts => Cdms.Model.Ipaffs.ChedppNotAcceptableReasonReasonEnum.DocNcts,
    Cdms.Types.Ipaffs.ChedppNotAcceptableReasonReasonEnum.DocNco => Cdms.Model.Ipaffs.ChedppNotAcceptableReasonReasonEnum.DocNco,
    Cdms.Types.Ipaffs.ChedppNotAcceptableReasonReasonEnum.DocOrii => Cdms.Model.Ipaffs.ChedppNotAcceptableReasonReasonEnum.DocOrii,
    Cdms.Types.Ipaffs.ChedppNotAcceptableReasonReasonEnum.DocOrsr => Cdms.Model.Ipaffs.ChedppNotAcceptableReasonReasonEnum.DocOrsr,
    Cdms.Types.Ipaffs.ChedppNotAcceptableReasonReasonEnum.OriOrrnu => Cdms.Model.Ipaffs.ChedppNotAcceptableReasonReasonEnum.OriOrrnu,
    Cdms.Types.Ipaffs.ChedppNotAcceptableReasonReasonEnum.PhyOrpp => Cdms.Model.Ipaffs.ChedppNotAcceptableReasonReasonEnum.PhyOrpp,
    Cdms.Types.Ipaffs.ChedppNotAcceptableReasonReasonEnum.PhyOrho => Cdms.Model.Ipaffs.ChedppNotAcceptableReasonReasonEnum.PhyOrho,
    Cdms.Types.Ipaffs.ChedppNotAcceptableReasonReasonEnum.PhyIs => Cdms.Model.Ipaffs.ChedppNotAcceptableReasonReasonEnum.PhyIs,
    Cdms.Types.Ipaffs.ChedppNotAcceptableReasonReasonEnum.PhyOrsr => Cdms.Model.Ipaffs.ChedppNotAcceptableReasonReasonEnum.PhyOrsr,
    Cdms.Types.Ipaffs.ChedppNotAcceptableReasonReasonEnum.OthCnl => Cdms.Model.Ipaffs.ChedppNotAcceptableReasonReasonEnum.OthCnl,
    Cdms.Types.Ipaffs.ChedppNotAcceptableReasonReasonEnum.OthO => Cdms.Model.Ipaffs.ChedppNotAcceptableReasonReasonEnum.OthO,

    _ => throw new ArgumentOutOfRangeException(nameof(from), from, null)
};
}
        

}


