//------------------------------------------------------------------------------
// <auto-generated>
	//     This code was generated from a template.
	//
	//     Manual changes to this file may cause unexpected behavior in your application.
	//     Manual changes to this file will be overwritten if the code is regenerated.
	//
//</auto-generated>
//------------------------------------------------------------------------------
#nullable enable


namespace Cdms.Types.Ipaffs.Mapping;

public static class CommodityChecksMapper
{
	public static Cdms.Model.Ipaffs.CommodityChecks Map(Cdms.Types.Ipaffs.CommodityChecks from)
	{
	if(from is null)
	{
		return default!;
	}
		var to = new Cdms.Model.Ipaffs.CommodityChecks ();
to.UniqueComplementId = from?.UniqueComplementId;
            to.Checks = from?.Checks?.Select(x => InspectionCheckMapper.Map(x)).ToArray();
                to.ValidityPeriod = from?.ValidityPeriod;
            	return to;
	}
}

