//------------------------------------------------------------------------------
// <auto-generated>
    //     This code was generated from a template.
    //
    //     Manual changes to this file may cause unexpected behavior in your application.
    //     Manual changes to this file will be overwritten if the code is regenerated.
    // </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Cdms.Types.Ipaffs.Mapping;

public static class CommodityRiskResultExitRiskDecisionEnumMapper
{
public static Cdms.Model.Ipaffs.CommodityRiskResultExitRiskDecisionEnum? Map(Cdms.Types.Ipaffs.CommodityRiskResultExitRiskDecisionEnum? from)
{
if(from == null)
{
return default!;
}
return from switch
{
Cdms.Types.Ipaffs.CommodityRiskResultExitRiskDecisionEnum.Required => Cdms.Model.Ipaffs.CommodityRiskResultExitRiskDecisionEnum.Required,
    Cdms.Types.Ipaffs.CommodityRiskResultExitRiskDecisionEnum.Notrequired => Cdms.Model.Ipaffs.CommodityRiskResultExitRiskDecisionEnum.Notrequired,
    Cdms.Types.Ipaffs.CommodityRiskResultExitRiskDecisionEnum.Inconclusive => Cdms.Model.Ipaffs.CommodityRiskResultExitRiskDecisionEnum.Inconclusive,
     
};
}
        

}


