//------------------------------------------------------------------------------
// <auto-generated>
    //     This code was generated from a template.
    //
    //     Manual changes to this file may cause unexpected behavior in your application.
    //     Manual changes to this file will be overwritten if the code is regenerated.
    // </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Cdms.Types.Ipaffs.Mapping;

public static class CommodityRiskResultPhsiDecisionEnumMapper
{
public static Cdms.Model.Ipaffs.CommodityRiskResultPhsiDecisionEnum? Map(Cdms.Types.Ipaffs.CommodityRiskResultPhsiDecisionEnum? from)
{
if(from == null)
{
return default!;
}
return from switch
{
Cdms.Types.Ipaffs.CommodityRiskResultPhsiDecisionEnum.Required => Cdms.Model.Ipaffs.CommodityRiskResultPhsiDecisionEnum.Required,
    Cdms.Types.Ipaffs.CommodityRiskResultPhsiDecisionEnum.Notrequired => Cdms.Model.Ipaffs.CommodityRiskResultPhsiDecisionEnum.Notrequired,

    _ => throw new ArgumentOutOfRangeException(nameof(from), from, null)
};
}
        

}


