//------------------------------------------------------------------------------
// <auto-generated>
    //     This code was generated from a template.
    //
    //     Manual changes to this file may cause unexpected behavior in your application.
    //     Manual changes to this file will be overwritten if the code is regenerated.
    // </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Cdms.Types.Ipaffs.Mapping;

public static class CommodityRiskResultPhsiClassificationEnumMapper
{
public static Cdms.Model.Ipaffs.CommodityRiskResultPhsiClassificationEnum? Map(Cdms.Types.Ipaffs.CommodityRiskResultPhsiClassificationEnum? from)
{
if(from == null)
{
return default!;
}
return from switch
{
Cdms.Types.Ipaffs.CommodityRiskResultPhsiClassificationEnum.Mandatory => Cdms.Model.Ipaffs.CommodityRiskResultPhsiClassificationEnum.Mandatory,
    Cdms.Types.Ipaffs.CommodityRiskResultPhsiClassificationEnum.Reduced => Cdms.Model.Ipaffs.CommodityRiskResultPhsiClassificationEnum.Reduced,
    Cdms.Types.Ipaffs.CommodityRiskResultPhsiClassificationEnum.Controlled => Cdms.Model.Ipaffs.CommodityRiskResultPhsiClassificationEnum.Controlled,

    _ => throw new ArgumentOutOfRangeException(nameof(from), from, null)
};
}
        

}


