//------------------------------------------------------------------------------
// <auto-generated>
    //     This code was generated from a template.
    //
    //     Manual changes to this file may cause unexpected behavior in your application.
    //     Manual changes to this file will be overwritten if the code is regenerated.
    // </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Cdms.Types.Ipaffs.Mapping;

public static class ConsignmentCheckIdentityCheckNotDoneReasonEnumMapper
{
public static Cdms.Model.Ipaffs.ConsignmentCheckIdentityCheckNotDoneReasonEnum? Map(Cdms.Types.Ipaffs.ConsignmentCheckIdentityCheckNotDoneReasonEnum? from)
{
if(from == null)
{
return default!;
}
return from switch
{
Cdms.Types.Ipaffs.ConsignmentCheckIdentityCheckNotDoneReasonEnum.ReducedChecksRegime => Cdms.Model.Ipaffs.ConsignmentCheckIdentityCheckNotDoneReasonEnum.ReducedChecksRegime,
    Cdms.Types.Ipaffs.ConsignmentCheckIdentityCheckNotDoneReasonEnum.NotRequired => Cdms.Model.Ipaffs.ConsignmentCheckIdentityCheckNotDoneReasonEnum.NotRequired,
     
};
}
        

}


