//------------------------------------------------------------------------------
// <auto-generated>
	//     This code was generated from a template.
	//
	//     Manual changes to this file may cause unexpected behavior in your application.
	//     Manual changes to this file will be overwritten if the code is regenerated.
	//
//</auto-generated>
//------------------------------------------------------------------------------
#nullable enable


namespace Cdms.Types.Ipaffs.Mapping;

public static class ConsignmentCheckMapper
{
	public static Cdms.Model.Ipaffs.ConsignmentCheck Map(Cdms.Types.Ipaffs.ConsignmentCheck from)
	{
	if(from is null)
	{
		return default!;
	}
		var to = new Cdms.Model.Ipaffs.ConsignmentCheck ();
to.EuStandard = from?.EuStandard;
            to.AdditionalGuarantees = from?.AdditionalGuarantees;
            to.DocumentCheckResult = from?.DocumentCheckResult;
            to.NationalRequirements = from?.NationalRequirements;
            to.IdentityCheckDone = from?.IdentityCheckDone;
            to.IdentityCheckType = ConsignmentCheckIdentityCheckTypeEnumMapper.Map(from?.IdentityCheckType);
                to.IdentityCheckResult = from?.IdentityCheckResult;
            to.IdentityCheckNotDoneReason = ConsignmentCheckIdentityCheckNotDoneReasonEnumMapper.Map(from?.IdentityCheckNotDoneReason);
                to.PhysicalCheckDone = from?.PhysicalCheckDone;
            to.PhysicalCheckResult = from?.PhysicalCheckResult;
            to.PhysicalCheckNotDoneReason = ConsignmentCheckPhysicalCheckNotDoneReasonEnumMapper.Map(from?.PhysicalCheckNotDoneReason);
                to.PhysicalCheckOtherText = from?.PhysicalCheckOtherText;
            to.WelfareCheck = from?.WelfareCheck;
            to.NumberOfAnimalsChecked = from?.NumberOfAnimalsChecked;
            to.LaboratoryCheckDone = from?.LaboratoryCheckDone;
            to.LaboratoryCheckResult = from?.LaboratoryCheckResult;
            	return to;
	}
}

