//------------------------------------------------------------------------------
// <auto-generated>
    //     This code was generated from a template.
    //
    //     Manual changes to this file may cause unexpected behavior in your application.
    //     Manual changes to this file will be overwritten if the code is regenerated.
    // </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Cdms.Types.Ipaffs.Mapping;

public static class ConsignmentCheckIdentityCheckTypeEnumMapper
{
public static Cdms.Model.Ipaffs.ConsignmentCheckIdentityCheckTypeEnum? Map(Cdms.Types.Ipaffs.ConsignmentCheckIdentityCheckTypeEnum? from)
{
if(from == null)
{
return default!;
}
return from switch
{
Cdms.Types.Ipaffs.ConsignmentCheckIdentityCheckTypeEnum.SealCheck => Cdms.Model.Ipaffs.ConsignmentCheckIdentityCheckTypeEnum.SealCheck,
    Cdms.Types.Ipaffs.ConsignmentCheckIdentityCheckTypeEnum.FullIdentityCheck => Cdms.Model.Ipaffs.ConsignmentCheckIdentityCheckTypeEnum.FullIdentityCheck,
    Cdms.Types.Ipaffs.ConsignmentCheckIdentityCheckTypeEnum.NotDone => Cdms.Model.Ipaffs.ConsignmentCheckIdentityCheckTypeEnum.NotDone,
     
};
}
        

}


