//------------------------------------------------------------------------------
// <auto-generated>
	//     This code was generated from a template.
	//
	//     Manual changes to this file may cause unexpected behavior in your application.
	//     Manual changes to this file will be overwritten if the code is regenerated.
	//
//</auto-generated>
//------------------------------------------------------------------------------
#nullable enable


namespace Cdms.Types.Ipaffs.Mapping;

public static class ContactDetailsMapper
{
	public static Cdms.Model.Ipaffs.ContactDetails Map(Cdms.Types.Ipaffs.ContactDetails from)
	{
	if(from is null)
	{
		return default!;
	}
		var to = new Cdms.Model.Ipaffs.ContactDetails ();
to.Name = from.Name;
            to.Telephone = from.Telephone;
            to.Email = from.Email;
            to.Agent = from.Agent;
            	return to;
	}
}

