//------------------------------------------------------------------------------
// <auto-generated>
    //     This code was generated from a template.
    //
    //     Manual changes to this file may cause unexpected behavior in your application.
    //     Manual changes to this file will be overwritten if the code is regenerated.
    // </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Cdms.Types.Ipaffs.Mapping;

public static class ControlAuthorityIuuOptionEnumMapper
{
public static Cdms.Model.Ipaffs.ControlAuthorityIuuOptionEnum? Map(Cdms.Types.Ipaffs.ControlAuthorityIuuOptionEnum? from)
{
if(from == null)
{
return default!;
}
return from switch
{
Cdms.Types.Ipaffs.ControlAuthorityIuuOptionEnum.Iuuok => Cdms.Model.Ipaffs.ControlAuthorityIuuOptionEnum.Iuuok,
    Cdms.Types.Ipaffs.ControlAuthorityIuuOptionEnum.Iuuna => Cdms.Model.Ipaffs.ControlAuthorityIuuOptionEnum.Iuuna,
    Cdms.Types.Ipaffs.ControlAuthorityIuuOptionEnum.IUUNotCompliant => Cdms.Model.Ipaffs.ControlAuthorityIuuOptionEnum.IUUNotCompliant,
     
};
}
        

}


