//------------------------------------------------------------------------------
// <auto-generated>
    //     This code was generated from a template.
    //
    //     Manual changes to this file may cause unexpected behavior in your application.
    //     Manual changes to this file will be overwritten if the code is regenerated.
    // </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Cdms.Types.Ipaffs.Mapping;

public static class DecisionNotAcceptableActionQuarantineImposedReasonEnumMapper
{
public static Cdms.Model.Ipaffs.DecisionNotAcceptableActionQuarantineImposedReasonEnum? Map(Cdms.Types.Ipaffs.DecisionNotAcceptableActionQuarantineImposedReasonEnum? from)
{
if(from == null)
{
return default!;
}
return from switch
{
Cdms.Types.Ipaffs.DecisionNotAcceptableActionQuarantineImposedReasonEnum.ContaminatedProducts => Cdms.Model.Ipaffs.DecisionNotAcceptableActionQuarantineImposedReasonEnum.ContaminatedProducts,
    Cdms.Types.Ipaffs.DecisionNotAcceptableActionQuarantineImposedReasonEnum.InterceptedPart => Cdms.Model.Ipaffs.DecisionNotAcceptableActionQuarantineImposedReasonEnum.InterceptedPart,
    Cdms.Types.Ipaffs.DecisionNotAcceptableActionQuarantineImposedReasonEnum.PackagingMaterial => Cdms.Model.Ipaffs.DecisionNotAcceptableActionQuarantineImposedReasonEnum.PackagingMaterial,
    Cdms.Types.Ipaffs.DecisionNotAcceptableActionQuarantineImposedReasonEnum.Other => Cdms.Model.Ipaffs.DecisionNotAcceptableActionQuarantineImposedReasonEnum.Other,
     
};
}
        

}


