//------------------------------------------------------------------------------
// <auto-generated>
    //     This code was generated from a template.
    //
    //     Manual changes to this file may cause unexpected behavior in your application.
    //     Manual changes to this file will be overwritten if the code is regenerated.
    // </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Cdms.Types.Ipaffs.Mapping;

public static class DecisionDecisionEnumMapper
{
public static Cdms.Model.Ipaffs.DecisionDecisionEnum? Map(Cdms.Types.Ipaffs.DecisionDecisionEnum? from)
{
if(from == null)
{
return default!;
}
return from switch
{
Cdms.Types.Ipaffs.DecisionDecisionEnum.NonAcceptable => Cdms.Model.Ipaffs.DecisionDecisionEnum.NonAcceptable,
    Cdms.Types.Ipaffs.DecisionDecisionEnum.AcceptableForInternalMarket => Cdms.Model.Ipaffs.DecisionDecisionEnum.AcceptableForInternalMarket,
    Cdms.Types.Ipaffs.DecisionDecisionEnum.AcceptableIfChanneled => Cdms.Model.Ipaffs.DecisionDecisionEnum.AcceptableIfChanneled,
    Cdms.Types.Ipaffs.DecisionDecisionEnum.AcceptableForTranshipment => Cdms.Model.Ipaffs.DecisionDecisionEnum.AcceptableForTranshipment,
    Cdms.Types.Ipaffs.DecisionDecisionEnum.AcceptableForTransit => Cdms.Model.Ipaffs.DecisionDecisionEnum.AcceptableForTransit,
    Cdms.Types.Ipaffs.DecisionDecisionEnum.AcceptableForTemporaryImport => Cdms.Model.Ipaffs.DecisionDecisionEnum.AcceptableForTemporaryImport,
    Cdms.Types.Ipaffs.DecisionDecisionEnum.AcceptableForSpecificWarehouse => Cdms.Model.Ipaffs.DecisionDecisionEnum.AcceptableForSpecificWarehouse,
    Cdms.Types.Ipaffs.DecisionDecisionEnum.AcceptableForPrivateImport => Cdms.Model.Ipaffs.DecisionDecisionEnum.AcceptableForPrivateImport,
    Cdms.Types.Ipaffs.DecisionDecisionEnum.AcceptableForTransfer => Cdms.Model.Ipaffs.DecisionDecisionEnum.AcceptableForTransfer,
    Cdms.Types.Ipaffs.DecisionDecisionEnum.HorseReEntry => Cdms.Model.Ipaffs.DecisionDecisionEnum.HorseReEntry,
     
};
}
        

}


