//------------------------------------------------------------------------------
// <auto-generated>
    //     This code was generated from a template.
    //
    //     Manual changes to this file may cause unexpected behavior in your application.
    //     Manual changes to this file will be overwritten if the code is regenerated.
    // </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Cdms.Types.Ipaffs.Mapping;

public static class DecisionNotAcceptableActionDestructionReasonEnumMapper
{
public static Cdms.Model.Ipaffs.DecisionNotAcceptableActionDestructionReasonEnum? Map(Cdms.Types.Ipaffs.DecisionNotAcceptableActionDestructionReasonEnum? from)
{
if(from == null)
{
return default!;
}
return from switch
{
Cdms.Types.Ipaffs.DecisionNotAcceptableActionDestructionReasonEnum.ContaminatedProducts => Cdms.Model.Ipaffs.DecisionNotAcceptableActionDestructionReasonEnum.ContaminatedProducts,
    Cdms.Types.Ipaffs.DecisionNotAcceptableActionDestructionReasonEnum.InterceptedPart => Cdms.Model.Ipaffs.DecisionNotAcceptableActionDestructionReasonEnum.InterceptedPart,
    Cdms.Types.Ipaffs.DecisionNotAcceptableActionDestructionReasonEnum.PackagingMaterial => Cdms.Model.Ipaffs.DecisionNotAcceptableActionDestructionReasonEnum.PackagingMaterial,
    Cdms.Types.Ipaffs.DecisionNotAcceptableActionDestructionReasonEnum.Other => Cdms.Model.Ipaffs.DecisionNotAcceptableActionDestructionReasonEnum.Other,

    _ => throw new ArgumentOutOfRangeException(nameof(from), from, null)
};
}
        

}


