//------------------------------------------------------------------------------
// <auto-generated>
    //     This code was generated from a template.
    //
    //     Manual changes to this file may cause unexpected behavior in your application.
    //     Manual changes to this file will be overwritten if the code is regenerated.
    // </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Cdms.Types.Ipaffs.Mapping;

public static class DecisionSpecificWarehouseNonConformingConsignmentEnumMapper
{
    public static Cdms.Model.Ipaffs.DecisionSpecificWarehouseNonConformingConsignmentEnum? Map(
        Cdms.Types.Ipaffs.DecisionSpecificWarehouseNonConformingConsignmentEnum? from)
    {
        if (from == null)
        {
            return default!;
        }

        return from switch
        {
            Cdms.Types.Ipaffs.DecisionSpecificWarehouseNonConformingConsignmentEnum.CustomWarehouse => Cdms.Model.Ipaffs
                .DecisionSpecificWarehouseNonConformingConsignmentEnum.CustomWarehouse,
            Cdms.Types.Ipaffs.DecisionSpecificWarehouseNonConformingConsignmentEnum.FreeZoneOrFreeWarehouse => Cdms
                .Model.Ipaffs.DecisionSpecificWarehouseNonConformingConsignmentEnum.FreeZoneOrFreeWarehouse,
            Cdms.Types.Ipaffs.DecisionSpecificWarehouseNonConformingConsignmentEnum.ShipSupplier => Cdms.Model.Ipaffs
                .DecisionSpecificWarehouseNonConformingConsignmentEnum.ShipSupplier,
            Cdms.Types.Ipaffs.DecisionSpecificWarehouseNonConformingConsignmentEnum.Ship => Cdms.Model.Ipaffs
                .DecisionSpecificWarehouseNonConformingConsignmentEnum.Ship,

            _ => throw new ArgumentOutOfRangeException(nameof(from), from, null)
        };
    }


}


