//------------------------------------------------------------------------------
// <auto-generated>
    //     This code was generated from a template.
    //
    //     Manual changes to this file may cause unexpected behavior in your application.
    //     Manual changes to this file will be overwritten if the code is regenerated.
    // </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Cdms.Types.Ipaffs.Mapping;

public static class DecisionNotAcceptableActionEntryRefusalReasonEnumMapper
{
public static Cdms.Model.Ipaffs.DecisionNotAcceptableActionEntryRefusalReasonEnum? Map(Cdms.Types.Ipaffs.DecisionNotAcceptableActionEntryRefusalReasonEnum? from)
{
if(from == null)
{
return default!;
}
return from switch
{
Cdms.Types.Ipaffs.DecisionNotAcceptableActionEntryRefusalReasonEnum.ContaminatedProducts => Cdms.Model.Ipaffs.DecisionNotAcceptableActionEntryRefusalReasonEnum.ContaminatedProducts,
    Cdms.Types.Ipaffs.DecisionNotAcceptableActionEntryRefusalReasonEnum.InterceptedPart => Cdms.Model.Ipaffs.DecisionNotAcceptableActionEntryRefusalReasonEnum.InterceptedPart,
    Cdms.Types.Ipaffs.DecisionNotAcceptableActionEntryRefusalReasonEnum.PackagingMaterial => Cdms.Model.Ipaffs.DecisionNotAcceptableActionEntryRefusalReasonEnum.PackagingMaterial,
    Cdms.Types.Ipaffs.DecisionNotAcceptableActionEntryRefusalReasonEnum.MeansOfTransport => Cdms.Model.Ipaffs.DecisionNotAcceptableActionEntryRefusalReasonEnum.MeansOfTransport,
    Cdms.Types.Ipaffs.DecisionNotAcceptableActionEntryRefusalReasonEnum.Other => Cdms.Model.Ipaffs.DecisionNotAcceptableActionEntryRefusalReasonEnum.Other,
     
};
}
        

}


