//------------------------------------------------------------------------------
// <auto-generated>
    //     This code was generated from a template.
    //
    //     Manual changes to this file may cause unexpected behavior in your application.
    //     Manual changes to this file will be overwritten if the code is regenerated.
    // </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Cdms.Types.Ipaffs.Mapping;

public static class DecisionFreeCirculationPurposeEnumMapper
{
public static Cdms.Model.Ipaffs.DecisionFreeCirculationPurposeEnum? Map(Cdms.Types.Ipaffs.DecisionFreeCirculationPurposeEnum? from)
{
if(from == null)
{
return default!;
}
return from switch
{
Cdms.Types.Ipaffs.DecisionFreeCirculationPurposeEnum.AnimalFeedingStuff => Cdms.Model.Ipaffs.DecisionFreeCirculationPurposeEnum.AnimalFeedingStuff,
    Cdms.Types.Ipaffs.DecisionFreeCirculationPurposeEnum.HumanConsumption => Cdms.Model.Ipaffs.DecisionFreeCirculationPurposeEnum.HumanConsumption,
    Cdms.Types.Ipaffs.DecisionFreeCirculationPurposeEnum.PharmaceuticalUse => Cdms.Model.Ipaffs.DecisionFreeCirculationPurposeEnum.PharmaceuticalUse,
    Cdms.Types.Ipaffs.DecisionFreeCirculationPurposeEnum.TechnicalUse => Cdms.Model.Ipaffs.DecisionFreeCirculationPurposeEnum.TechnicalUse,
    Cdms.Types.Ipaffs.DecisionFreeCirculationPurposeEnum.FurtherProcess => Cdms.Model.Ipaffs.DecisionFreeCirculationPurposeEnum.FurtherProcess,
    Cdms.Types.Ipaffs.DecisionFreeCirculationPurposeEnum.Other => Cdms.Model.Ipaffs.DecisionFreeCirculationPurposeEnum.Other,

    _ => throw new ArgumentOutOfRangeException(nameof(from), from, null)
};
}
        

}


