//------------------------------------------------------------------------------
// <auto-generated>
    //     This code was generated from a template.
    //
    //     Manual changes to this file may cause unexpected behavior in your application.
    //     Manual changes to this file will be overwritten if the code is regenerated.
    // </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Cdms.Types.Ipaffs.Mapping;

public static class DetailsOnReExportTransportTypeEnumMapper
{
public static Cdms.Model.Ipaffs.DetailsOnReExportTransportTypeEnum? Map(Cdms.Types.Ipaffs.DetailsOnReExportTransportTypeEnum? from)
{
if(from == null)
{
return default!;
}
return from switch
{
Cdms.Types.Ipaffs.DetailsOnReExportTransportTypeEnum.Rail => Cdms.Model.Ipaffs.DetailsOnReExportTransportTypeEnum.Rail,
    Cdms.Types.Ipaffs.DetailsOnReExportTransportTypeEnum.Plane => Cdms.Model.Ipaffs.DetailsOnReExportTransportTypeEnum.Plane,
    Cdms.Types.Ipaffs.DetailsOnReExportTransportTypeEnum.Ship => Cdms.Model.Ipaffs.DetailsOnReExportTransportTypeEnum.Ship,
    Cdms.Types.Ipaffs.DetailsOnReExportTransportTypeEnum.Road => Cdms.Model.Ipaffs.DetailsOnReExportTransportTypeEnum.Road,
    Cdms.Types.Ipaffs.DetailsOnReExportTransportTypeEnum.Other => Cdms.Model.Ipaffs.DetailsOnReExportTransportTypeEnum.Other,
    Cdms.Types.Ipaffs.DetailsOnReExportTransportTypeEnum.CShipRoad => Cdms.Model.Ipaffs.DetailsOnReExportTransportTypeEnum.CShipRoad,
    Cdms.Types.Ipaffs.DetailsOnReExportTransportTypeEnum.CShipRail => Cdms.Model.Ipaffs.DetailsOnReExportTransportTypeEnum.CShipRail,
     
};
}
        

}


