//------------------------------------------------------------------------------
// <auto-generated>
    //     This code was generated from a template.
    //
    //     Manual changes to this file may cause unexpected behavior in your application.
    //     Manual changes to this file will be overwritten if the code is regenerated.
    // </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Cdms.Types.Ipaffs.Mapping;

public static class EconomicOperatorStatusEnumMapper
{
public static Cdms.Model.Ipaffs.EconomicOperatorStatusEnum? Map(Cdms.Types.Ipaffs.EconomicOperatorStatusEnum? from)
{
if(from == null)
{
return default!;
}
return from switch
{
Cdms.Types.Ipaffs.EconomicOperatorStatusEnum.Approved => Cdms.Model.Ipaffs.EconomicOperatorStatusEnum.Approved,
    Cdms.Types.Ipaffs.EconomicOperatorStatusEnum.Nonapproved => Cdms.Model.Ipaffs.EconomicOperatorStatusEnum.Nonapproved,
    Cdms.Types.Ipaffs.EconomicOperatorStatusEnum.Suspended => Cdms.Model.Ipaffs.EconomicOperatorStatusEnum.Suspended,
     
};
}
        

}


