//------------------------------------------------------------------------------
// <auto-generated>
    //     This code was generated from a template.
    //
    //     Manual changes to this file may cause unexpected behavior in your application.
    //     Manual changes to this file will be overwritten if the code is regenerated.
    // </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Cdms.Types.Ipaffs.Mapping;

public static class ExternalReferenceSystemEnumMapper
{
public static Cdms.Model.Ipaffs.ExternalReferenceSystemEnum? Map(Cdms.Types.Ipaffs.ExternalReferenceSystemEnum? from)
{
if(from == null)
{
return default!;
}
return from switch
{
Cdms.Types.Ipaffs.ExternalReferenceSystemEnum.Ecert => Cdms.Model.Ipaffs.ExternalReferenceSystemEnum.Ecert,
    Cdms.Types.Ipaffs.ExternalReferenceSystemEnum.Ephyto => Cdms.Model.Ipaffs.ExternalReferenceSystemEnum.Ephyto,
    Cdms.Types.Ipaffs.ExternalReferenceSystemEnum.Enotification => Cdms.Model.Ipaffs.ExternalReferenceSystemEnum.Enotification,
    Cdms.Types.Ipaffs.ExternalReferenceSystemEnum.Ncts => Cdms.Model.Ipaffs.ExternalReferenceSystemEnum.Ncts,
     
};
}
        

}


