//------------------------------------------------------------------------------
// <auto-generated>
    //     This code was generated from a template.
    //
    //     Manual changes to this file may cause unexpected behavior in your application.
    //     Manual changes to this file will be overwritten if the code is regenerated.
    // </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Cdms.Types.Ipaffs.Mapping;

public static class FeedbackInformationAuthorityTypeEnumMapper
{
public static Cdms.Model.Ipaffs.FeedbackInformationAuthorityTypeEnum? Map(Cdms.Types.Ipaffs.FeedbackInformationAuthorityTypeEnum? from)
{
if(from == null)
{
return default!;
}
return from switch
{
Cdms.Types.Ipaffs.FeedbackInformationAuthorityTypeEnum.Exitbip => Cdms.Model.Ipaffs.FeedbackInformationAuthorityTypeEnum.Exitbip,
    Cdms.Types.Ipaffs.FeedbackInformationAuthorityTypeEnum.Finalbip => Cdms.Model.Ipaffs.FeedbackInformationAuthorityTypeEnum.Finalbip,
    Cdms.Types.Ipaffs.FeedbackInformationAuthorityTypeEnum.Localvetunit => Cdms.Model.Ipaffs.FeedbackInformationAuthorityTypeEnum.Localvetunit,
    Cdms.Types.Ipaffs.FeedbackInformationAuthorityTypeEnum.Inspunit => Cdms.Model.Ipaffs.FeedbackInformationAuthorityTypeEnum.Inspunit,
     
};
}
        

}


