//------------------------------------------------------------------------------
// <auto-generated>
	//     This code was generated from a template.
	//
	//     Manual changes to this file may cause unexpected behavior in your application.
	//     Manual changes to this file will be overwritten if the code is regenerated.
	//
//</auto-generated>
//------------------------------------------------------------------------------
#nullable enable


namespace Cdms.Types.Ipaffs.Mapping;

public static class IdentificationDetailsMapper
{
	public static Cdms.Model.Ipaffs.IdentificationDetails Map(Cdms.Types.Ipaffs.IdentificationDetails from)
	{
	if(from is null)
	{
		return default!;
	}
		var to = new Cdms.Model.Ipaffs.IdentificationDetails ();
to.IdentificationDetail = from?.IdentificationDetail;
            to.IdentificationDescription = from?.IdentificationDescription;
            	return to;
	}
}

