//------------------------------------------------------------------------------
// <auto-generated>
	//     This code was generated from a template.
	//
	//     Manual changes to this file may cause unexpected behavior in your application.
	//     Manual changes to this file will be overwritten if the code is regenerated.
	//
//</auto-generated>
//------------------------------------------------------------------------------
#nullable enable


namespace Cdms.Types.Ipaffs.Mapping;

public static class InspectorMapper
{
	public static Cdms.Model.Ipaffs.Inspector Map(Cdms.Types.Ipaffs.Inspector from)
	{
	if(from is null)
	{
		return default!;
	}
		var to = new Cdms.Model.Ipaffs.Inspector ();
to.Name = from?.Name;
            to.Phone = from?.Phone;
            to.Email = from?.Email;
            	return to;
	}
}

