//------------------------------------------------------------------------------
// <auto-generated>
    //     This code was generated from a template.
    //
    //     Manual changes to this file may cause unexpected behavior in your application.
    //     Manual changes to this file will be overwritten if the code is regenerated.
    // </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Cdms.Types.Ipaffs.Mapping;

public static class InspectionCheckTypeEnumMapper
{
public static Cdms.Model.Ipaffs.InspectionCheckTypeEnum? Map(Cdms.Types.Ipaffs.InspectionCheckTypeEnum? from)
{
if(from == null)
{
return default!;
}
return from switch
{
Cdms.Types.Ipaffs.InspectionCheckTypeEnum.PhsiDocument => Cdms.Model.Ipaffs.InspectionCheckTypeEnum.PhsiDocument,
    Cdms.Types.Ipaffs.InspectionCheckTypeEnum.PhsiIdentity => Cdms.Model.Ipaffs.InspectionCheckTypeEnum.PhsiIdentity,
    Cdms.Types.Ipaffs.InspectionCheckTypeEnum.PhsiPhysical => Cdms.Model.Ipaffs.InspectionCheckTypeEnum.PhsiPhysical,
    Cdms.Types.Ipaffs.InspectionCheckTypeEnum.Hmi => Cdms.Model.Ipaffs.InspectionCheckTypeEnum.Hmi,
     
};
}
        

}


