//------------------------------------------------------------------------------
// <auto-generated>
    //     This code was generated from a template.
    //
    //     Manual changes to this file may cause unexpected behavior in your application.
    //     Manual changes to this file will be overwritten if the code is regenerated.
    // </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Cdms.Types.Ipaffs.Mapping;

public static class InspectionRequiredEnumMapper
{
public static Cdms.Model.Ipaffs.InspectionRequiredEnum? Map(Cdms.Types.Ipaffs.InspectionRequiredEnum? from)
{
if(from == null)
{
return default!;
}
return from switch
{
Cdms.Types.Ipaffs.InspectionRequiredEnum.Required => Cdms.Model.Ipaffs.InspectionRequiredEnum.Required,
    Cdms.Types.Ipaffs.InspectionRequiredEnum.Inconclusive => Cdms.Model.Ipaffs.InspectionRequiredEnum.Inconclusive,
    Cdms.Types.Ipaffs.InspectionRequiredEnum.NotRequired => Cdms.Model.Ipaffs.InspectionRequiredEnum.NotRequired,
     
};
}
        

}


