//------------------------------------------------------------------------------
// <auto-generated>
	//     This code was generated from a template.
	//
	//     Manual changes to this file may cause unexpected behavior in your application.
	//     Manual changes to this file will be overwritten if the code is regenerated.
	//
//</auto-generated>
//------------------------------------------------------------------------------
#nullable enable


namespace Cdms.Types.Ipaffs.Mapping;

public static class InternationalTelephoneMapper
{
	public static Cdms.Model.Ipaffs.InternationalTelephone Map(Cdms.Types.Ipaffs.InternationalTelephone from)
	{
	if(from is null)
	{
		return default!;
	}
		var to = new Cdms.Model.Ipaffs.InternationalTelephone ();
to.CountryCode = from.CountryCode;
            to.SubscriberNumber = from.SubscriberNumber;
            	return to;
	}
}

