//------------------------------------------------------------------------------
// <auto-generated>
    //     This code was generated from a template.
    //
    //     Manual changes to this file may cause unexpected behavior in your application.
    //     Manual changes to this file will be overwritten if the code is regenerated.
    // </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Cdms.Types.Ipaffs.Mapping;

public static class IpaffsCommodityRiskResultExitRiskDecisionEnumMapper
{
public static Cdms.Model.Ipaffs.IpaffsCommodityRiskResultExitRiskDecisionEnum? Map(Cdms.Types.Ipaffs.IpaffsCommodityRiskResultExitRiskDecisionEnum? from)
{
if(from == null)
{
return default!;
}
return from switch
{
Cdms.Types.Ipaffs.IpaffsCommodityRiskResultExitRiskDecisionEnum.Required => Cdms.Model.Ipaffs.IpaffsCommodityRiskResultExitRiskDecisionEnum.Required,
    Cdms.Types.Ipaffs.IpaffsCommodityRiskResultExitRiskDecisionEnum.Notrequired => Cdms.Model.Ipaffs.IpaffsCommodityRiskResultExitRiskDecisionEnum.Notrequired,
    Cdms.Types.Ipaffs.IpaffsCommodityRiskResultExitRiskDecisionEnum.Inconclusive => Cdms.Model.Ipaffs.IpaffsCommodityRiskResultExitRiskDecisionEnum.Inconclusive,
     
};
}
        

}


