//------------------------------------------------------------------------------
// <auto-generated>
	//     This code was generated from a template.
	//
	//     Manual changes to this file may cause unexpected behavior in your application.
	//     Manual changes to this file will be overwritten if the code is regenerated.
	//
//</auto-generated>
//------------------------------------------------------------------------------
#nullable enable


namespace Cdms.Types.Ipaffs.Mapping;

public static class IpaffsJourneyRiskCategorisationResultMapper
{
	public static Cdms.Model.Ipaffs.IpaffsJourneyRiskCategorisationResult Map(Cdms.Types.Ipaffs.IpaffsJourneyRiskCategorisationResult from)
	{
	if(from is null)
	{
		return default!;
	}
		var to = new Cdms.Model.Ipaffs.IpaffsJourneyRiskCategorisationResult ();
to.RiskLevel = IpaffsJourneyRiskCategorisationResultRiskLevelEnumMapper.Map(from?.RiskLevel);
                to.RiskLevelMethod = IpaffsJourneyRiskCategorisationResultRiskLevelMethodEnumMapper.Map(from?.RiskLevelMethod);
                to.RiskLevelDateTime = from.RiskLevelDateTime;
            	return to;
	}
}

