//------------------------------------------------------------------------------
// <auto-generated>
    //     This code was generated from a template.
    //
    //     Manual changes to this file may cause unexpected behavior in your application.
    //     Manual changes to this file will be overwritten if the code is regenerated.
    // </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Cdms.Types.Ipaffs.Mapping;

public static class IpaffsInspectionRequiredEnumMapper
{
public static Cdms.Model.Ipaffs.IpaffsInspectionRequiredEnum? Map(Cdms.Types.Ipaffs.IpaffsInspectionRequiredEnum? from)
{
if(from == null)
{
return default!;
}
return from switch
{
Cdms.Types.Ipaffs.IpaffsInspectionRequiredEnum.Required => Cdms.Model.Ipaffs.IpaffsInspectionRequiredEnum.Required,
    Cdms.Types.Ipaffs.IpaffsInspectionRequiredEnum.Inconclusive => Cdms.Model.Ipaffs.IpaffsInspectionRequiredEnum.Inconclusive,
    Cdms.Types.Ipaffs.IpaffsInspectionRequiredEnum.NotRequired => Cdms.Model.Ipaffs.IpaffsInspectionRequiredEnum.NotRequired,
     
};
}
        

}


