//------------------------------------------------------------------------------
// <auto-generated>
    //     This code was generated from a template.
    //
    //     Manual changes to this file may cause unexpected behavior in your application.
    //     Manual changes to this file will be overwritten if the code is regenerated.
    // </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Cdms.Types.Ipaffs.Mapping;

public static class IpaffsDecisionNotAcceptableActionSpecialTreatmentReasonEnumMapper
{
public static Cdms.Model.Ipaffs.IpaffsDecisionNotAcceptableActionSpecialTreatmentReasonEnum? Map(Cdms.Types.Ipaffs.IpaffsDecisionNotAcceptableActionSpecialTreatmentReasonEnum? from)
{
if(from == null)
{
return default!;
}
return from switch
{
Cdms.Types.Ipaffs.IpaffsDecisionNotAcceptableActionSpecialTreatmentReasonEnum.ContaminatedProducts => Cdms.Model.Ipaffs.IpaffsDecisionNotAcceptableActionSpecialTreatmentReasonEnum.ContaminatedProducts,
    Cdms.Types.Ipaffs.IpaffsDecisionNotAcceptableActionSpecialTreatmentReasonEnum.InterceptedPart => Cdms.Model.Ipaffs.IpaffsDecisionNotAcceptableActionSpecialTreatmentReasonEnum.InterceptedPart,
    Cdms.Types.Ipaffs.IpaffsDecisionNotAcceptableActionSpecialTreatmentReasonEnum.PackagingMaterial => Cdms.Model.Ipaffs.IpaffsDecisionNotAcceptableActionSpecialTreatmentReasonEnum.PackagingMaterial,
    Cdms.Types.Ipaffs.IpaffsDecisionNotAcceptableActionSpecialTreatmentReasonEnum.Other => Cdms.Model.Ipaffs.IpaffsDecisionNotAcceptableActionSpecialTreatmentReasonEnum.Other,
     
};
}
        

}


