//------------------------------------------------------------------------------
// <auto-generated>
    //     This code was generated from a template.
    //
    //     Manual changes to this file may cause unexpected behavior in your application.
    //     Manual changes to this file will be overwritten if the code is regenerated.
    // </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Cdms.Types.Ipaffs.Mapping;

public static class IpaffsDecisionSpecificWarehouseNonConformingConsignmentEnumMapper
{
public static Cdms.Model.Ipaffs.IpaffsDecisionSpecificWarehouseNonConformingConsignmentEnum? Map(Cdms.Types.Ipaffs.IpaffsDecisionSpecificWarehouseNonConformingConsignmentEnum? from)
{
if(from == null)
{
return default!;
}
return from switch
{
Cdms.Types.Ipaffs.IpaffsDecisionSpecificWarehouseNonConformingConsignmentEnum.CustomWarehouse => Cdms.Model.Ipaffs.IpaffsDecisionSpecificWarehouseNonConformingConsignmentEnum.CustomWarehouse,
    Cdms.Types.Ipaffs.IpaffsDecisionSpecificWarehouseNonConformingConsignmentEnum.FreeZoneOrFreeWarehouse => Cdms.Model.Ipaffs.IpaffsDecisionSpecificWarehouseNonConformingConsignmentEnum.FreeZoneOrFreeWarehouse,
    Cdms.Types.Ipaffs.IpaffsDecisionSpecificWarehouseNonConformingConsignmentEnum.ShipSupplier => Cdms.Model.Ipaffs.IpaffsDecisionSpecificWarehouseNonConformingConsignmentEnum.ShipSupplier,
    Cdms.Types.Ipaffs.IpaffsDecisionSpecificWarehouseNonConformingConsignmentEnum.Ship => Cdms.Model.Ipaffs.IpaffsDecisionSpecificWarehouseNonConformingConsignmentEnum.Ship,
     
};
}
        

}


