//------------------------------------------------------------------------------
// <auto-generated>
    //     This code was generated from a template.
    //
    //     Manual changes to this file may cause unexpected behavior in your application.
    //     Manual changes to this file will be overwritten if the code is regenerated.
    // </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Cdms.Types.Ipaffs.Mapping;

public static class IpaffsJourneyRiskCategorisationResultRiskLevelEnumMapper
{
public static Cdms.Model.Ipaffs.IpaffsJourneyRiskCategorisationResultRiskLevelEnum? Map(Cdms.Types.Ipaffs.IpaffsJourneyRiskCategorisationResultRiskLevelEnum? from)
{
if(from == null)
{
return default!;
}
return from switch
{
Cdms.Types.Ipaffs.IpaffsJourneyRiskCategorisationResultRiskLevelEnum.High => Cdms.Model.Ipaffs.IpaffsJourneyRiskCategorisationResultRiskLevelEnum.High,
    Cdms.Types.Ipaffs.IpaffsJourneyRiskCategorisationResultRiskLevelEnum.Medium => Cdms.Model.Ipaffs.IpaffsJourneyRiskCategorisationResultRiskLevelEnum.Medium,
    Cdms.Types.Ipaffs.IpaffsJourneyRiskCategorisationResultRiskLevelEnum.Low => Cdms.Model.Ipaffs.IpaffsJourneyRiskCategorisationResultRiskLevelEnum.Low,
     
};
}
        

}


