//------------------------------------------------------------------------------
// <auto-generated>
    //     This code was generated from a template.
    //
    //     Manual changes to this file may cause unexpected behavior in your application.
    //     Manual changes to this file will be overwritten if the code is regenerated.
    // </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Cdms.Types.Ipaffs.Mapping;

public static class IpaffsDecisionNotAcceptableActionEnumMapper
{
public static Cdms.Model.Ipaffs.IpaffsDecisionNotAcceptableActionEnum? Map(Cdms.Types.Ipaffs.IpaffsDecisionNotAcceptableActionEnum? from)
{
if(from == null)
{
return default!;
}
return from switch
{
Cdms.Types.Ipaffs.IpaffsDecisionNotAcceptableActionEnum.Slaughter => Cdms.Model.Ipaffs.IpaffsDecisionNotAcceptableActionEnum.Slaughter,
    Cdms.Types.Ipaffs.IpaffsDecisionNotAcceptableActionEnum.Reexport => Cdms.Model.Ipaffs.IpaffsDecisionNotAcceptableActionEnum.Reexport,
    Cdms.Types.Ipaffs.IpaffsDecisionNotAcceptableActionEnum.Euthanasia => Cdms.Model.Ipaffs.IpaffsDecisionNotAcceptableActionEnum.Euthanasia,
    Cdms.Types.Ipaffs.IpaffsDecisionNotAcceptableActionEnum.Redispatching => Cdms.Model.Ipaffs.IpaffsDecisionNotAcceptableActionEnum.Redispatching,
    Cdms.Types.Ipaffs.IpaffsDecisionNotAcceptableActionEnum.Destruction => Cdms.Model.Ipaffs.IpaffsDecisionNotAcceptableActionEnum.Destruction,
    Cdms.Types.Ipaffs.IpaffsDecisionNotAcceptableActionEnum.Transformation => Cdms.Model.Ipaffs.IpaffsDecisionNotAcceptableActionEnum.Transformation,
    Cdms.Types.Ipaffs.IpaffsDecisionNotAcceptableActionEnum.Other => Cdms.Model.Ipaffs.IpaffsDecisionNotAcceptableActionEnum.Other,
    Cdms.Types.Ipaffs.IpaffsDecisionNotAcceptableActionEnum.EntryRefusal => Cdms.Model.Ipaffs.IpaffsDecisionNotAcceptableActionEnum.EntryRefusal,
    Cdms.Types.Ipaffs.IpaffsDecisionNotAcceptableActionEnum.QuarantineImposed => Cdms.Model.Ipaffs.IpaffsDecisionNotAcceptableActionEnum.QuarantineImposed,
    Cdms.Types.Ipaffs.IpaffsDecisionNotAcceptableActionEnum.SpecialTreatment => Cdms.Model.Ipaffs.IpaffsDecisionNotAcceptableActionEnum.SpecialTreatment,
    Cdms.Types.Ipaffs.IpaffsDecisionNotAcceptableActionEnum.IndustrialProcessing => Cdms.Model.Ipaffs.IpaffsDecisionNotAcceptableActionEnum.IndustrialProcessing,
    Cdms.Types.Ipaffs.IpaffsDecisionNotAcceptableActionEnum.ReDispatch => Cdms.Model.Ipaffs.IpaffsDecisionNotAcceptableActionEnum.ReDispatch,
    Cdms.Types.Ipaffs.IpaffsDecisionNotAcceptableActionEnum.UseForOtherPurposes => Cdms.Model.Ipaffs.IpaffsDecisionNotAcceptableActionEnum.UseForOtherPurposes,
     
};
}
        

}


