//------------------------------------------------------------------------------
// <auto-generated>
    //     This code was generated from a template.
    //
    //     Manual changes to this file may cause unexpected behavior in your application.
    //     Manual changes to this file will be overwritten if the code is regenerated.
    // </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Cdms.Types.Ipaffs.Mapping;

public static class IpaffsDecisionNotAcceptableActionUseForOtherPurposesReasonEnumMapper
{
public static Cdms.Model.Ipaffs.IpaffsDecisionNotAcceptableActionUseForOtherPurposesReasonEnum? Map(Cdms.Types.Ipaffs.IpaffsDecisionNotAcceptableActionUseForOtherPurposesReasonEnum? from)
{
if(from == null)
{
return default!;
}
return from switch
{
Cdms.Types.Ipaffs.IpaffsDecisionNotAcceptableActionUseForOtherPurposesReasonEnum.ContaminatedProducts => Cdms.Model.Ipaffs.IpaffsDecisionNotAcceptableActionUseForOtherPurposesReasonEnum.ContaminatedProducts,
    Cdms.Types.Ipaffs.IpaffsDecisionNotAcceptableActionUseForOtherPurposesReasonEnum.InterceptedPart => Cdms.Model.Ipaffs.IpaffsDecisionNotAcceptableActionUseForOtherPurposesReasonEnum.InterceptedPart,
    Cdms.Types.Ipaffs.IpaffsDecisionNotAcceptableActionUseForOtherPurposesReasonEnum.PackagingMaterial => Cdms.Model.Ipaffs.IpaffsDecisionNotAcceptableActionUseForOtherPurposesReasonEnum.PackagingMaterial,
    Cdms.Types.Ipaffs.IpaffsDecisionNotAcceptableActionUseForOtherPurposesReasonEnum.MeansOfTransport => Cdms.Model.Ipaffs.IpaffsDecisionNotAcceptableActionUseForOtherPurposesReasonEnum.MeansOfTransport,
    Cdms.Types.Ipaffs.IpaffsDecisionNotAcceptableActionUseForOtherPurposesReasonEnum.Other => Cdms.Model.Ipaffs.IpaffsDecisionNotAcceptableActionUseForOtherPurposesReasonEnum.Other,
     
};
}
        

}


