//------------------------------------------------------------------------------
// <auto-generated>
    //     This code was generated from a template.
    //
    //     Manual changes to this file may cause unexpected behavior in your application.
    //     Manual changes to this file will be overwritten if the code is regenerated.
    // </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Cdms.Types.Ipaffs.Mapping;

public static class IpaffsImportNotificationStatusEnumMapper
{
public static Cdms.Model.Ipaffs.IpaffsImportNotificationStatusEnum? Map(Cdms.Types.Ipaffs.IpaffsImportNotificationStatusEnum? from)
{
if(from == null)
{
return default!;
}
return from switch
{
Cdms.Types.Ipaffs.IpaffsImportNotificationStatusEnum.Draft => Cdms.Model.Ipaffs.IpaffsImportNotificationStatusEnum.Draft,
    Cdms.Types.Ipaffs.IpaffsImportNotificationStatusEnum.Submitted => Cdms.Model.Ipaffs.IpaffsImportNotificationStatusEnum.Submitted,
    Cdms.Types.Ipaffs.IpaffsImportNotificationStatusEnum.Validated => Cdms.Model.Ipaffs.IpaffsImportNotificationStatusEnum.Validated,
    Cdms.Types.Ipaffs.IpaffsImportNotificationStatusEnum.Rejected => Cdms.Model.Ipaffs.IpaffsImportNotificationStatusEnum.Rejected,
    Cdms.Types.Ipaffs.IpaffsImportNotificationStatusEnum.InProgress => Cdms.Model.Ipaffs.IpaffsImportNotificationStatusEnum.InProgress,
    Cdms.Types.Ipaffs.IpaffsImportNotificationStatusEnum.Amend => Cdms.Model.Ipaffs.IpaffsImportNotificationStatusEnum.Amend,
    Cdms.Types.Ipaffs.IpaffsImportNotificationStatusEnum.Modify => Cdms.Model.Ipaffs.IpaffsImportNotificationStatusEnum.Modify,
    Cdms.Types.Ipaffs.IpaffsImportNotificationStatusEnum.Replaced => Cdms.Model.Ipaffs.IpaffsImportNotificationStatusEnum.Replaced,
    Cdms.Types.Ipaffs.IpaffsImportNotificationStatusEnum.Cancelled => Cdms.Model.Ipaffs.IpaffsImportNotificationStatusEnum.Cancelled,
    Cdms.Types.Ipaffs.IpaffsImportNotificationStatusEnum.Deleted => Cdms.Model.Ipaffs.IpaffsImportNotificationStatusEnum.Deleted,
    Cdms.Types.Ipaffs.IpaffsImportNotificationStatusEnum.PartiallyRejected => Cdms.Model.Ipaffs.IpaffsImportNotificationStatusEnum.PartiallyRejected,
    Cdms.Types.Ipaffs.IpaffsImportNotificationStatusEnum.SplitConsignment => Cdms.Model.Ipaffs.IpaffsImportNotificationStatusEnum.SplitConsignment,
     
};
}
        

}


