//------------------------------------------------------------------------------
// <auto-generated>
    //     This code was generated from a template.
    //
    //     Manual changes to this file may cause unexpected behavior in your application.
    //     Manual changes to this file will be overwritten if the code is regenerated.
    // </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Cdms.Types.Ipaffs.Mapping;

public static class IpaffsEconomicOperatorTypeEnumMapper
{
public static Cdms.Model.Ipaffs.IpaffsEconomicOperatorTypeEnum? Map(Cdms.Types.Ipaffs.IpaffsEconomicOperatorTypeEnum? from)
{
if(from == null)
{
return default!;
}
return from switch
{
Cdms.Types.Ipaffs.IpaffsEconomicOperatorTypeEnum.Consignee => Cdms.Model.Ipaffs.IpaffsEconomicOperatorTypeEnum.Consignee,
    Cdms.Types.Ipaffs.IpaffsEconomicOperatorTypeEnum.Destination => Cdms.Model.Ipaffs.IpaffsEconomicOperatorTypeEnum.Destination,
    Cdms.Types.Ipaffs.IpaffsEconomicOperatorTypeEnum.Exporter => Cdms.Model.Ipaffs.IpaffsEconomicOperatorTypeEnum.Exporter,
    Cdms.Types.Ipaffs.IpaffsEconomicOperatorTypeEnum.Importer => Cdms.Model.Ipaffs.IpaffsEconomicOperatorTypeEnum.Importer,
    Cdms.Types.Ipaffs.IpaffsEconomicOperatorTypeEnum.Charity => Cdms.Model.Ipaffs.IpaffsEconomicOperatorTypeEnum.Charity,
    Cdms.Types.Ipaffs.IpaffsEconomicOperatorTypeEnum.CommercialTransporter => Cdms.Model.Ipaffs.IpaffsEconomicOperatorTypeEnum.CommercialTransporter,
    Cdms.Types.Ipaffs.IpaffsEconomicOperatorTypeEnum.CommercialTransporterUserAdded => Cdms.Model.Ipaffs.IpaffsEconomicOperatorTypeEnum.CommercialTransporterUserAdded,
    Cdms.Types.Ipaffs.IpaffsEconomicOperatorTypeEnum.PrivateTransporter => Cdms.Model.Ipaffs.IpaffsEconomicOperatorTypeEnum.PrivateTransporter,
    Cdms.Types.Ipaffs.IpaffsEconomicOperatorTypeEnum.TemporaryAddress => Cdms.Model.Ipaffs.IpaffsEconomicOperatorTypeEnum.TemporaryAddress,
    Cdms.Types.Ipaffs.IpaffsEconomicOperatorTypeEnum.PremisesOfOrigin => Cdms.Model.Ipaffs.IpaffsEconomicOperatorTypeEnum.PremisesOfOrigin,
    Cdms.Types.Ipaffs.IpaffsEconomicOperatorTypeEnum.OrganisationBranchAddress => Cdms.Model.Ipaffs.IpaffsEconomicOperatorTypeEnum.OrganisationBranchAddress,
    Cdms.Types.Ipaffs.IpaffsEconomicOperatorTypeEnum.Packer => Cdms.Model.Ipaffs.IpaffsEconomicOperatorTypeEnum.Packer,
    Cdms.Types.Ipaffs.IpaffsEconomicOperatorTypeEnum.Pod => Cdms.Model.Ipaffs.IpaffsEconomicOperatorTypeEnum.Pod,
     
};
}
        

}


