//------------------------------------------------------------------------------
// <auto-generated>
	//     This code was generated from a template.
	//
	//     Manual changes to this file may cause unexpected behavior in your application.
	//     Manual changes to this file will be overwritten if the code is regenerated.
	//
//</auto-generated>
//------------------------------------------------------------------------------
#nullable enable


namespace Cdms.Types.Ipaffs.Mapping;

public static class IpaffsMeansOfTransportMapper
{
	public static Cdms.Model.Ipaffs.IpaffsMeansOfTransport Map(Cdms.Types.Ipaffs.IpaffsMeansOfTransport from)
	{
	if(from is null)
	{
		return default!;
	}
		var to = new Cdms.Model.Ipaffs.IpaffsMeansOfTransport ();
to.IpaffsType = IpaffsMeansOfTransportTypeEnumMapper.Map(from?.IpaffsType);
                to.Document = from.Document;
            to.IpaffsId = from.IpaffsId;
            	return to;
	}
}

