//------------------------------------------------------------------------------
// <auto-generated>
	//     This code was generated from a template.
	//
	//     Manual changes to this file may cause unexpected behavior in your application.
	//     Manual changes to this file will be overwritten if the code is regenerated.
	//
//</auto-generated>
//------------------------------------------------------------------------------
#nullable enable


namespace Cdms.Types.Ipaffs.Mapping;

public static class IpaffsRouteMapper
{
	public static Cdms.Model.Ipaffs.IpaffsRoute Map(Cdms.Types.Ipaffs.IpaffsRoute from)
	{
	if(from is null)
	{
		return default!;
	}
		var to = new Cdms.Model.Ipaffs.IpaffsRoute ();
to.TransitingStates = from.TransitingStates;
            	return to;
	}
}

