//------------------------------------------------------------------------------
// <auto-generated>
    //     This code was generated from a template.
    //
    //     Manual changes to this file may cause unexpected behavior in your application.
    //     Manual changes to this file will be overwritten if the code is regenerated.
    // </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Cdms.Types.Ipaffs.Mapping;

public static class IpaffsPartOneProvideCtcMrnEnumMapper
{
public static Cdms.Model.Ipaffs.IpaffsPartOneProvideCtcMrnEnum? Map(Cdms.Types.Ipaffs.IpaffsPartOneProvideCtcMrnEnum? from)
{
if(from == null)
{
return default!;
}
return from switch
{
Cdms.Types.Ipaffs.IpaffsPartOneProvideCtcMrnEnum.Yes => Cdms.Model.Ipaffs.IpaffsPartOneProvideCtcMrnEnum.Yes,
    Cdms.Types.Ipaffs.IpaffsPartOneProvideCtcMrnEnum.YesAddLater => Cdms.Model.Ipaffs.IpaffsPartOneProvideCtcMrnEnum.YesAddLater,
    Cdms.Types.Ipaffs.IpaffsPartOneProvideCtcMrnEnum.No => Cdms.Model.Ipaffs.IpaffsPartOneProvideCtcMrnEnum.No,
     
};
}
        

}


