//------------------------------------------------------------------------------
// <auto-generated>
    //     This code was generated from a template.
    //
    //     Manual changes to this file may cause unexpected behavior in your application.
    //     Manual changes to this file will be overwritten if the code is regenerated.
    // </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Cdms.Types.Ipaffs.Mapping;

public static class IpaffsPartyTypeEnumMapper
{
public static Cdms.Model.Ipaffs.IpaffsPartyTypeEnum? Map(Cdms.Types.Ipaffs.IpaffsPartyTypeEnum? from)
{
if(from == null)
{
return default!;
}
return from switch
{
Cdms.Types.Ipaffs.IpaffsPartyTypeEnum.CommercialTransporter => Cdms.Model.Ipaffs.IpaffsPartyTypeEnum.CommercialTransporter,
    Cdms.Types.Ipaffs.IpaffsPartyTypeEnum.PrivateTransporter => Cdms.Model.Ipaffs.IpaffsPartyTypeEnum.PrivateTransporter,
     
};
}
        

}


