//------------------------------------------------------------------------------
// <auto-generated>
    //     This code was generated from a template.
    //
    //     Manual changes to this file may cause unexpected behavior in your application.
    //     Manual changes to this file will be overwritten if the code is regenerated.
    // </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Cdms.Types.Ipaffs.Mapping;

public static class IpaffsMeansOfTransportTypeEnumMapper
{
public static Cdms.Model.Ipaffs.IpaffsMeansOfTransportTypeEnum? Map(Cdms.Types.Ipaffs.IpaffsMeansOfTransportTypeEnum? from)
{
if(from == null)
{
return default!;
}
return from switch
{
Cdms.Types.Ipaffs.IpaffsMeansOfTransportTypeEnum.Aeroplane => Cdms.Model.Ipaffs.IpaffsMeansOfTransportTypeEnum.Aeroplane,
    Cdms.Types.Ipaffs.IpaffsMeansOfTransportTypeEnum.RoadVehicle => Cdms.Model.Ipaffs.IpaffsMeansOfTransportTypeEnum.RoadVehicle,
    Cdms.Types.Ipaffs.IpaffsMeansOfTransportTypeEnum.RailwayWagon => Cdms.Model.Ipaffs.IpaffsMeansOfTransportTypeEnum.RailwayWagon,
    Cdms.Types.Ipaffs.IpaffsMeansOfTransportTypeEnum.Ship => Cdms.Model.Ipaffs.IpaffsMeansOfTransportTypeEnum.Ship,
    Cdms.Types.Ipaffs.IpaffsMeansOfTransportTypeEnum.Other => Cdms.Model.Ipaffs.IpaffsMeansOfTransportTypeEnum.Other,
    Cdms.Types.Ipaffs.IpaffsMeansOfTransportTypeEnum.RoadVehicleAeroplane => Cdms.Model.Ipaffs.IpaffsMeansOfTransportTypeEnum.RoadVehicleAeroplane,
    Cdms.Types.Ipaffs.IpaffsMeansOfTransportTypeEnum.ShipRailwayWagon => Cdms.Model.Ipaffs.IpaffsMeansOfTransportTypeEnum.ShipRailwayWagon,
    Cdms.Types.Ipaffs.IpaffsMeansOfTransportTypeEnum.ShipRoadVehicle => Cdms.Model.Ipaffs.IpaffsMeansOfTransportTypeEnum.ShipRoadVehicle,
     
};
}
        

}


