//------------------------------------------------------------------------------
// <auto-generated>
    //     This code was generated from a template.
    //
    //     Manual changes to this file may cause unexpected behavior in your application.
    //     Manual changes to this file will be overwritten if the code is regenerated.
    // </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Cdms.Types.Ipaffs.Mapping;

public static class IpaffsLaboratoryTestResultConclusionEnumMapper
{
public static Cdms.Model.Ipaffs.IpaffsLaboratoryTestResultConclusionEnum? Map(Cdms.Types.Ipaffs.IpaffsLaboratoryTestResultConclusionEnum? from)
{
if(from == null)
{
return default!;
}
return from switch
{
Cdms.Types.Ipaffs.IpaffsLaboratoryTestResultConclusionEnum.Satisfactory => Cdms.Model.Ipaffs.IpaffsLaboratoryTestResultConclusionEnum.Satisfactory,
    Cdms.Types.Ipaffs.IpaffsLaboratoryTestResultConclusionEnum.NotSatisfactory => Cdms.Model.Ipaffs.IpaffsLaboratoryTestResultConclusionEnum.NotSatisfactory,
    Cdms.Types.Ipaffs.IpaffsLaboratoryTestResultConclusionEnum.NotInterpretable => Cdms.Model.Ipaffs.IpaffsLaboratoryTestResultConclusionEnum.NotInterpretable,
    Cdms.Types.Ipaffs.IpaffsLaboratoryTestResultConclusionEnum.Pending => Cdms.Model.Ipaffs.IpaffsLaboratoryTestResultConclusionEnum.Pending,
     
};
}
        

}


