//------------------------------------------------------------------------------
// <auto-generated>
	//     This code was generated from a template.
	//
	//     Manual changes to this file may cause unexpected behavior in your application.
	//     Manual changes to this file will be overwritten if the code is regenerated.
	//
//</auto-generated>
//------------------------------------------------------------------------------
#nullable enable


namespace Cdms.Types.Ipaffs.Mapping;

public static class IpaffsValidationMessageCodeMapper
{
	public static Cdms.Model.Ipaffs.IpaffsValidationMessageCode Map(Cdms.Types.Ipaffs.IpaffsValidationMessageCode from)
	{
	if(from is null)
	{
		return default!;
	}
		var to = new Cdms.Model.Ipaffs.IpaffsValidationMessageCode ();
to.Field = from.Field;
            to.Code = from.Code;
            	return to;
	}
}

