//------------------------------------------------------------------------------
// <auto-generated>
    //     This code was generated from a template.
    //
    //     Manual changes to this file may cause unexpected behavior in your application.
    //     Manual changes to this file will be overwritten if the code is regenerated.
    // </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Cdms.Types.Ipaffs.Mapping;

public static class IpaffsDecisionNotAcceptableActionReDispatchReasonEnumMapper
{
public static Cdms.Model.Ipaffs.IpaffsDecisionNotAcceptableActionReDispatchReasonEnum? Map(Cdms.Types.Ipaffs.IpaffsDecisionNotAcceptableActionReDispatchReasonEnum? from)
{
if(from == null)
{
return default!;
}
return from switch
{
Cdms.Types.Ipaffs.IpaffsDecisionNotAcceptableActionReDispatchReasonEnum.ContaminatedProducts => Cdms.Model.Ipaffs.IpaffsDecisionNotAcceptableActionReDispatchReasonEnum.ContaminatedProducts,
    Cdms.Types.Ipaffs.IpaffsDecisionNotAcceptableActionReDispatchReasonEnum.InterceptedPart => Cdms.Model.Ipaffs.IpaffsDecisionNotAcceptableActionReDispatchReasonEnum.InterceptedPart,
    Cdms.Types.Ipaffs.IpaffsDecisionNotAcceptableActionReDispatchReasonEnum.PackagingMaterial => Cdms.Model.Ipaffs.IpaffsDecisionNotAcceptableActionReDispatchReasonEnum.PackagingMaterial,
    Cdms.Types.Ipaffs.IpaffsDecisionNotAcceptableActionReDispatchReasonEnum.MeansOfTransport => Cdms.Model.Ipaffs.IpaffsDecisionNotAcceptableActionReDispatchReasonEnum.MeansOfTransport,
    Cdms.Types.Ipaffs.IpaffsDecisionNotAcceptableActionReDispatchReasonEnum.Other => Cdms.Model.Ipaffs.IpaffsDecisionNotAcceptableActionReDispatchReasonEnum.Other,
     
};
}
        

}


