//------------------------------------------------------------------------------
// <auto-generated>
	//     This code was generated from a template.
	//
	//     Manual changes to this file may cause unexpected behavior in your application.
	//     Manual changes to this file will be overwritten if the code is regenerated.
	//
//</auto-generated>
//------------------------------------------------------------------------------
#nullable enable


namespace Cdms.Types.Ipaffs.Mapping;

public static class IpaffsControlMapper
{
	public static Cdms.Model.Ipaffs.IpaffsControl Map(Cdms.Types.Ipaffs.IpaffsControl from)
	{
	if(from is null)
	{
		return default!;
	}
		var to = new Cdms.Model.Ipaffs.IpaffsControl ();
to.FeedbackInformation = IpaffsFeedbackInformationMapper.Map(from?.FeedbackInformation);
                to.DetailsOnReExport = IpaffsDetailsOnReExportMapper.Map(from?.DetailsOnReExport);
                to.OfficialInspector = IpaffsOfficialInspectorMapper.Map(from?.OfficialInspector);
                to.ConsignmentLeave = IpaffsControlConsignmentLeaveEnumMapper.Map(from?.ConsignmentLeave);
                	return to;
	}
}

