//------------------------------------------------------------------------------
// <auto-generated>
    //     This code was generated from a template.
    //
    //     Manual changes to this file may cause unexpected behavior in your application.
    //     Manual changes to this file will be overwritten if the code is regenerated.
    // </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Cdms.Types.Ipaffs.Mapping;

public static class IpaffsAccompanyingDocumentDocumentTypeEnumMapper
{
public static Cdms.Model.Ipaffs.IpaffsAccompanyingDocumentDocumentTypeEnum? Map(Cdms.Types.Ipaffs.IpaffsAccompanyingDocumentDocumentTypeEnum? from)
{
if(from == null)
{
return default!;
}
return from switch
{
Cdms.Types.Ipaffs.IpaffsAccompanyingDocumentDocumentTypeEnum.AirWaybill => Cdms.Model.Ipaffs.IpaffsAccompanyingDocumentDocumentTypeEnum.AirWaybill,
    Cdms.Types.Ipaffs.IpaffsAccompanyingDocumentDocumentTypeEnum.BillOfLading => Cdms.Model.Ipaffs.IpaffsAccompanyingDocumentDocumentTypeEnum.BillOfLading,
    Cdms.Types.Ipaffs.IpaffsAccompanyingDocumentDocumentTypeEnum.CargoManifest => Cdms.Model.Ipaffs.IpaffsAccompanyingDocumentDocumentTypeEnum.CargoManifest,
    Cdms.Types.Ipaffs.IpaffsAccompanyingDocumentDocumentTypeEnum.CatchCertificate => Cdms.Model.Ipaffs.IpaffsAccompanyingDocumentDocumentTypeEnum.CatchCertificate,
    Cdms.Types.Ipaffs.IpaffsAccompanyingDocumentDocumentTypeEnum.CommercialDocument => Cdms.Model.Ipaffs.IpaffsAccompanyingDocumentDocumentTypeEnum.CommercialDocument,
    Cdms.Types.Ipaffs.IpaffsAccompanyingDocumentDocumentTypeEnum.CommercialInvoice => Cdms.Model.Ipaffs.IpaffsAccompanyingDocumentDocumentTypeEnum.CommercialInvoice,
    Cdms.Types.Ipaffs.IpaffsAccompanyingDocumentDocumentTypeEnum.ConformityCertificate => Cdms.Model.Ipaffs.IpaffsAccompanyingDocumentDocumentTypeEnum.ConformityCertificate,
    Cdms.Types.Ipaffs.IpaffsAccompanyingDocumentDocumentTypeEnum.ContainerManifest => Cdms.Model.Ipaffs.IpaffsAccompanyingDocumentDocumentTypeEnum.ContainerManifest,
    Cdms.Types.Ipaffs.IpaffsAccompanyingDocumentDocumentTypeEnum.CustomsDeclaration => Cdms.Model.Ipaffs.IpaffsAccompanyingDocumentDocumentTypeEnum.CustomsDeclaration,
    Cdms.Types.Ipaffs.IpaffsAccompanyingDocumentDocumentTypeEnum.Docom => Cdms.Model.Ipaffs.IpaffsAccompanyingDocumentDocumentTypeEnum.Docom,
    Cdms.Types.Ipaffs.IpaffsAccompanyingDocumentDocumentTypeEnum.HealthCertificate => Cdms.Model.Ipaffs.IpaffsAccompanyingDocumentDocumentTypeEnum.HealthCertificate,
    Cdms.Types.Ipaffs.IpaffsAccompanyingDocumentDocumentTypeEnum.HeatTreatmentCertificate => Cdms.Model.Ipaffs.IpaffsAccompanyingDocumentDocumentTypeEnum.HeatTreatmentCertificate,
    Cdms.Types.Ipaffs.IpaffsAccompanyingDocumentDocumentTypeEnum.ImportPermit => Cdms.Model.Ipaffs.IpaffsAccompanyingDocumentDocumentTypeEnum.ImportPermit,
    Cdms.Types.Ipaffs.IpaffsAccompanyingDocumentDocumentTypeEnum.InspectionCertificate => Cdms.Model.Ipaffs.IpaffsAccompanyingDocumentDocumentTypeEnum.InspectionCertificate,
    Cdms.Types.Ipaffs.IpaffsAccompanyingDocumentDocumentTypeEnum.Itahc => Cdms.Model.Ipaffs.IpaffsAccompanyingDocumentDocumentTypeEnum.Itahc,
    Cdms.Types.Ipaffs.IpaffsAccompanyingDocumentDocumentTypeEnum.JourneyLog => Cdms.Model.Ipaffs.IpaffsAccompanyingDocumentDocumentTypeEnum.JourneyLog,
    Cdms.Types.Ipaffs.IpaffsAccompanyingDocumentDocumentTypeEnum.LaboratorySamplingResultsForAflatoxin => Cdms.Model.Ipaffs.IpaffsAccompanyingDocumentDocumentTypeEnum.LaboratorySamplingResultsForAflatoxin,
    Cdms.Types.Ipaffs.IpaffsAccompanyingDocumentDocumentTypeEnum.LatestVeterinaryHealthCertificate => Cdms.Model.Ipaffs.IpaffsAccompanyingDocumentDocumentTypeEnum.LatestVeterinaryHealthCertificate,
    Cdms.Types.Ipaffs.IpaffsAccompanyingDocumentDocumentTypeEnum.LetterOfAuthority => Cdms.Model.Ipaffs.IpaffsAccompanyingDocumentDocumentTypeEnum.LetterOfAuthority,
    Cdms.Types.Ipaffs.IpaffsAccompanyingDocumentDocumentTypeEnum.LicenseOrAuthorisation => Cdms.Model.Ipaffs.IpaffsAccompanyingDocumentDocumentTypeEnum.LicenseOrAuthorisation,
    Cdms.Types.Ipaffs.IpaffsAccompanyingDocumentDocumentTypeEnum.MycotoxinCertification => Cdms.Model.Ipaffs.IpaffsAccompanyingDocumentDocumentTypeEnum.MycotoxinCertification,
    Cdms.Types.Ipaffs.IpaffsAccompanyingDocumentDocumentTypeEnum.OriginCertificate => Cdms.Model.Ipaffs.IpaffsAccompanyingDocumentDocumentTypeEnum.OriginCertificate,
    Cdms.Types.Ipaffs.IpaffsAccompanyingDocumentDocumentTypeEnum.Other => Cdms.Model.Ipaffs.IpaffsAccompanyingDocumentDocumentTypeEnum.Other,
    Cdms.Types.Ipaffs.IpaffsAccompanyingDocumentDocumentTypeEnum.PhytosanitaryCertificate => Cdms.Model.Ipaffs.IpaffsAccompanyingDocumentDocumentTypeEnum.PhytosanitaryCertificate,
    Cdms.Types.Ipaffs.IpaffsAccompanyingDocumentDocumentTypeEnum.ProcessingStatement => Cdms.Model.Ipaffs.IpaffsAccompanyingDocumentDocumentTypeEnum.ProcessingStatement,
    Cdms.Types.Ipaffs.IpaffsAccompanyingDocumentDocumentTypeEnum.ProofOfStorage => Cdms.Model.Ipaffs.IpaffsAccompanyingDocumentDocumentTypeEnum.ProofOfStorage,
    Cdms.Types.Ipaffs.IpaffsAccompanyingDocumentDocumentTypeEnum.RailwayBill => Cdms.Model.Ipaffs.IpaffsAccompanyingDocumentDocumentTypeEnum.RailwayBill,
    Cdms.Types.Ipaffs.IpaffsAccompanyingDocumentDocumentTypeEnum.SeaWaybill => Cdms.Model.Ipaffs.IpaffsAccompanyingDocumentDocumentTypeEnum.SeaWaybill,
    Cdms.Types.Ipaffs.IpaffsAccompanyingDocumentDocumentTypeEnum.VeterinaryHealthCertificate => Cdms.Model.Ipaffs.IpaffsAccompanyingDocumentDocumentTypeEnum.VeterinaryHealthCertificate,
    Cdms.Types.Ipaffs.IpaffsAccompanyingDocumentDocumentTypeEnum.ListOfIngredients => Cdms.Model.Ipaffs.IpaffsAccompanyingDocumentDocumentTypeEnum.ListOfIngredients,
    Cdms.Types.Ipaffs.IpaffsAccompanyingDocumentDocumentTypeEnum.PackingList => Cdms.Model.Ipaffs.IpaffsAccompanyingDocumentDocumentTypeEnum.PackingList,
    Cdms.Types.Ipaffs.IpaffsAccompanyingDocumentDocumentTypeEnum.RoadConsignmentNote => Cdms.Model.Ipaffs.IpaffsAccompanyingDocumentDocumentTypeEnum.RoadConsignmentNote,
     
};
}
        

}


