//------------------------------------------------------------------------------
// <auto-generated>
    //     This code was generated from a template.
    //
    //     Manual changes to this file may cause unexpected behavior in your application.
    //     Manual changes to this file will be overwritten if the code is regenerated.
    // </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Cdms.Types.Ipaffs.Mapping;

public static class IpaffsAnimalCertificationEnumMapper
{
public static Cdms.Model.Ipaffs.IpaffsAnimalCertificationEnum? Map(Cdms.Types.Ipaffs.IpaffsAnimalCertificationEnum? from)
{
if(from == null)
{
return default!;
}
return from switch
{
Cdms.Types.Ipaffs.IpaffsAnimalCertificationEnum.AnimalFeedingStuff => Cdms.Model.Ipaffs.IpaffsAnimalCertificationEnum.AnimalFeedingStuff,
    Cdms.Types.Ipaffs.IpaffsAnimalCertificationEnum.Approved => Cdms.Model.Ipaffs.IpaffsAnimalCertificationEnum.Approved,
    Cdms.Types.Ipaffs.IpaffsAnimalCertificationEnum.ArtificialReproduction => Cdms.Model.Ipaffs.IpaffsAnimalCertificationEnum.ArtificialReproduction,
    Cdms.Types.Ipaffs.IpaffsAnimalCertificationEnum.Breeding => Cdms.Model.Ipaffs.IpaffsAnimalCertificationEnum.Breeding,
    Cdms.Types.Ipaffs.IpaffsAnimalCertificationEnum.Circus => Cdms.Model.Ipaffs.IpaffsAnimalCertificationEnum.Circus,
    Cdms.Types.Ipaffs.IpaffsAnimalCertificationEnum.CommercialSale => Cdms.Model.Ipaffs.IpaffsAnimalCertificationEnum.CommercialSale,
    Cdms.Types.Ipaffs.IpaffsAnimalCertificationEnum.CommercialSaleOrChangeOfOwnership => Cdms.Model.Ipaffs.IpaffsAnimalCertificationEnum.CommercialSaleOrChangeOfOwnership,
    Cdms.Types.Ipaffs.IpaffsAnimalCertificationEnum.Fattening => Cdms.Model.Ipaffs.IpaffsAnimalCertificationEnum.Fattening,
    Cdms.Types.Ipaffs.IpaffsAnimalCertificationEnum.GameRestocking => Cdms.Model.Ipaffs.IpaffsAnimalCertificationEnum.GameRestocking,
    Cdms.Types.Ipaffs.IpaffsAnimalCertificationEnum.HumanConsumption => Cdms.Model.Ipaffs.IpaffsAnimalCertificationEnum.HumanConsumption,
    Cdms.Types.Ipaffs.IpaffsAnimalCertificationEnum.InternalMarket => Cdms.Model.Ipaffs.IpaffsAnimalCertificationEnum.InternalMarket,
    Cdms.Types.Ipaffs.IpaffsAnimalCertificationEnum.Other => Cdms.Model.Ipaffs.IpaffsAnimalCertificationEnum.Other,
    Cdms.Types.Ipaffs.IpaffsAnimalCertificationEnum.PersonallyOwnedPetsNotForRehoming => Cdms.Model.Ipaffs.IpaffsAnimalCertificationEnum.PersonallyOwnedPetsNotForRehoming,
    Cdms.Types.Ipaffs.IpaffsAnimalCertificationEnum.Pets => Cdms.Model.Ipaffs.IpaffsAnimalCertificationEnum.Pets,
    Cdms.Types.Ipaffs.IpaffsAnimalCertificationEnum.Production => Cdms.Model.Ipaffs.IpaffsAnimalCertificationEnum.Production,
    Cdms.Types.Ipaffs.IpaffsAnimalCertificationEnum.Quarantine => Cdms.Model.Ipaffs.IpaffsAnimalCertificationEnum.Quarantine,
    Cdms.Types.Ipaffs.IpaffsAnimalCertificationEnum.RacingCompetition => Cdms.Model.Ipaffs.IpaffsAnimalCertificationEnum.RacingCompetition,
    Cdms.Types.Ipaffs.IpaffsAnimalCertificationEnum.RegisteredEquidae => Cdms.Model.Ipaffs.IpaffsAnimalCertificationEnum.RegisteredEquidae,
    Cdms.Types.Ipaffs.IpaffsAnimalCertificationEnum.Registered => Cdms.Model.Ipaffs.IpaffsAnimalCertificationEnum.Registered,
    Cdms.Types.Ipaffs.IpaffsAnimalCertificationEnum.RejectedOrReturnedConsignment => Cdms.Model.Ipaffs.IpaffsAnimalCertificationEnum.RejectedOrReturnedConsignment,
    Cdms.Types.Ipaffs.IpaffsAnimalCertificationEnum.Relaying => Cdms.Model.Ipaffs.IpaffsAnimalCertificationEnum.Relaying,
    Cdms.Types.Ipaffs.IpaffsAnimalCertificationEnum.RescueRehoming => Cdms.Model.Ipaffs.IpaffsAnimalCertificationEnum.RescueRehoming,
    Cdms.Types.Ipaffs.IpaffsAnimalCertificationEnum.Research => Cdms.Model.Ipaffs.IpaffsAnimalCertificationEnum.Research,
    Cdms.Types.Ipaffs.IpaffsAnimalCertificationEnum.Slaughter => Cdms.Model.Ipaffs.IpaffsAnimalCertificationEnum.Slaughter,
    Cdms.Types.Ipaffs.IpaffsAnimalCertificationEnum.TechnicalPharmaceuticalUse => Cdms.Model.Ipaffs.IpaffsAnimalCertificationEnum.TechnicalPharmaceuticalUse,
    Cdms.Types.Ipaffs.IpaffsAnimalCertificationEnum.Transit => Cdms.Model.Ipaffs.IpaffsAnimalCertificationEnum.Transit,
    Cdms.Types.Ipaffs.IpaffsAnimalCertificationEnum.ZooCollection => Cdms.Model.Ipaffs.IpaffsAnimalCertificationEnum.ZooCollection,
     
};
}
        

}


