//------------------------------------------------------------------------------
// <auto-generated>
    //     This code was generated from a template.
    //
    //     Manual changes to this file may cause unexpected behavior in your application.
    //     Manual changes to this file will be overwritten if the code is regenerated.
    // </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Cdms.Types.Ipaffs.Mapping;

public static class IpaffsCommodityRiskResultHmiDecisionEnumMapper
{
public static Cdms.Model.Ipaffs.IpaffsCommodityRiskResultHmiDecisionEnum? Map(Cdms.Types.Ipaffs.IpaffsCommodityRiskResultHmiDecisionEnum? from)
{
if(from == null)
{
return default!;
}
return from switch
{
Cdms.Types.Ipaffs.IpaffsCommodityRiskResultHmiDecisionEnum.Required => Cdms.Model.Ipaffs.IpaffsCommodityRiskResultHmiDecisionEnum.Required,
    Cdms.Types.Ipaffs.IpaffsCommodityRiskResultHmiDecisionEnum.Notrequired => Cdms.Model.Ipaffs.IpaffsCommodityRiskResultHmiDecisionEnum.Notrequired,
     
};
}
        

}


