//------------------------------------------------------------------------------
// <auto-generated>
    //     This code was generated from a template.
    //
    //     Manual changes to this file may cause unexpected behavior in your application.
    //     Manual changes to this file will be overwritten if the code is regenerated.
    // </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Cdms.Types.Ipaffs.Mapping;

public static class IpaffsResultEnumMapper
{
public static Cdms.Model.Ipaffs.IpaffsResultEnum? Map(Cdms.Types.Ipaffs.IpaffsResultEnum? from)
{
if(from == null)
{
return default!;
}
return from switch
{
Cdms.Types.Ipaffs.IpaffsResultEnum.Satisfactory => Cdms.Model.Ipaffs.IpaffsResultEnum.Satisfactory,
    Cdms.Types.Ipaffs.IpaffsResultEnum.SatisfactoryFollowingOfficialIntervention => Cdms.Model.Ipaffs.IpaffsResultEnum.SatisfactoryFollowingOfficialIntervention,
    Cdms.Types.Ipaffs.IpaffsResultEnum.NotSatisfactory => Cdms.Model.Ipaffs.IpaffsResultEnum.NotSatisfactory,
    Cdms.Types.Ipaffs.IpaffsResultEnum.NotDone => Cdms.Model.Ipaffs.IpaffsResultEnum.NotDone,
    Cdms.Types.Ipaffs.IpaffsResultEnum.Derogation => Cdms.Model.Ipaffs.IpaffsResultEnum.Derogation,
    Cdms.Types.Ipaffs.IpaffsResultEnum.NotSet => Cdms.Model.Ipaffs.IpaffsResultEnum.NotSet,
     
};
}
        

}


