//------------------------------------------------------------------------------
// <auto-generated>
    //     This code was generated from a template.
    //
    //     Manual changes to this file may cause unexpected behavior in your application.
    //     Manual changes to this file will be overwritten if the code is regenerated.
    // </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Cdms.Types.Ipaffs.Mapping;

public static class IpaffsApplicantAnalysisTypeEnumMapper
{
public static Cdms.Model.Ipaffs.IpaffsApplicantAnalysisTypeEnum? Map(Cdms.Types.Ipaffs.IpaffsApplicantAnalysisTypeEnum? from)
{
if(from == null)
{
return default!;
}
return from switch
{
Cdms.Types.Ipaffs.IpaffsApplicantAnalysisTypeEnum.InitialAnalysis => Cdms.Model.Ipaffs.IpaffsApplicantAnalysisTypeEnum.InitialAnalysis,
    Cdms.Types.Ipaffs.IpaffsApplicantAnalysisTypeEnum.CounterAnalysis => Cdms.Model.Ipaffs.IpaffsApplicantAnalysisTypeEnum.CounterAnalysis,
    Cdms.Types.Ipaffs.IpaffsApplicantAnalysisTypeEnum.SecondExpertAnalysis => Cdms.Model.Ipaffs.IpaffsApplicantAnalysisTypeEnum.SecondExpertAnalysis,
     
};
}
        

}


