//------------------------------------------------------------------------------
// <auto-generated>
    //     This code was generated from a template.
    //
    //     Manual changes to this file may cause unexpected behavior in your application.
    //     Manual changes to this file will be overwritten if the code is regenerated.
    // </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Cdms.Types.Ipaffs.Mapping;

public static class IpaffsDecisionNotAcceptableActionIndustrialProcessingReasonEnumMapper
{
public static Cdms.Model.Ipaffs.IpaffsDecisionNotAcceptableActionIndustrialProcessingReasonEnum? Map(Cdms.Types.Ipaffs.IpaffsDecisionNotAcceptableActionIndustrialProcessingReasonEnum? from)
{
if(from == null)
{
return default!;
}
return from switch
{
Cdms.Types.Ipaffs.IpaffsDecisionNotAcceptableActionIndustrialProcessingReasonEnum.ContaminatedProducts => Cdms.Model.Ipaffs.IpaffsDecisionNotAcceptableActionIndustrialProcessingReasonEnum.ContaminatedProducts,
    Cdms.Types.Ipaffs.IpaffsDecisionNotAcceptableActionIndustrialProcessingReasonEnum.InterceptedPart => Cdms.Model.Ipaffs.IpaffsDecisionNotAcceptableActionIndustrialProcessingReasonEnum.InterceptedPart,
    Cdms.Types.Ipaffs.IpaffsDecisionNotAcceptableActionIndustrialProcessingReasonEnum.PackagingMaterial => Cdms.Model.Ipaffs.IpaffsDecisionNotAcceptableActionIndustrialProcessingReasonEnum.PackagingMaterial,
    Cdms.Types.Ipaffs.IpaffsDecisionNotAcceptableActionIndustrialProcessingReasonEnum.Other => Cdms.Model.Ipaffs.IpaffsDecisionNotAcceptableActionIndustrialProcessingReasonEnum.Other,
     
};
}
        

}


