//------------------------------------------------------------------------------
// <auto-generated>
    //     This code was generated from a template.
    //
    //     Manual changes to this file may cause unexpected behavior in your application.
    //     Manual changes to this file will be overwritten if the code is regenerated.
    // </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Cdms.Types.Ipaffs.Mapping;

public static class IpaffsPurposeInternalMarketPurposeEnumMapper
{
public static Cdms.Model.Ipaffs.IpaffsPurposeInternalMarketPurposeEnum? Map(Cdms.Types.Ipaffs.IpaffsPurposeInternalMarketPurposeEnum? from)
{
if(from == null)
{
return default!;
}
return from switch
{
Cdms.Types.Ipaffs.IpaffsPurposeInternalMarketPurposeEnum.AnimalFeedingStuff => Cdms.Model.Ipaffs.IpaffsPurposeInternalMarketPurposeEnum.AnimalFeedingStuff,
    Cdms.Types.Ipaffs.IpaffsPurposeInternalMarketPurposeEnum.HumanConsumption => Cdms.Model.Ipaffs.IpaffsPurposeInternalMarketPurposeEnum.HumanConsumption,
    Cdms.Types.Ipaffs.IpaffsPurposeInternalMarketPurposeEnum.PharmaceuticalUse => Cdms.Model.Ipaffs.IpaffsPurposeInternalMarketPurposeEnum.PharmaceuticalUse,
    Cdms.Types.Ipaffs.IpaffsPurposeInternalMarketPurposeEnum.TechnicalUse => Cdms.Model.Ipaffs.IpaffsPurposeInternalMarketPurposeEnum.TechnicalUse,
    Cdms.Types.Ipaffs.IpaffsPurposeInternalMarketPurposeEnum.Other => Cdms.Model.Ipaffs.IpaffsPurposeInternalMarketPurposeEnum.Other,
    Cdms.Types.Ipaffs.IpaffsPurposeInternalMarketPurposeEnum.CommercialSale => Cdms.Model.Ipaffs.IpaffsPurposeInternalMarketPurposeEnum.CommercialSale,
    Cdms.Types.Ipaffs.IpaffsPurposeInternalMarketPurposeEnum.CommercialSaleOrChangeOfOwnership => Cdms.Model.Ipaffs.IpaffsPurposeInternalMarketPurposeEnum.CommercialSaleOrChangeOfOwnership,
    Cdms.Types.Ipaffs.IpaffsPurposeInternalMarketPurposeEnum.Rescue => Cdms.Model.Ipaffs.IpaffsPurposeInternalMarketPurposeEnum.Rescue,
    Cdms.Types.Ipaffs.IpaffsPurposeInternalMarketPurposeEnum.Breeding => Cdms.Model.Ipaffs.IpaffsPurposeInternalMarketPurposeEnum.Breeding,
    Cdms.Types.Ipaffs.IpaffsPurposeInternalMarketPurposeEnum.Research => Cdms.Model.Ipaffs.IpaffsPurposeInternalMarketPurposeEnum.Research,
    Cdms.Types.Ipaffs.IpaffsPurposeInternalMarketPurposeEnum.RacingOrCompetition => Cdms.Model.Ipaffs.IpaffsPurposeInternalMarketPurposeEnum.RacingOrCompetition,
    Cdms.Types.Ipaffs.IpaffsPurposeInternalMarketPurposeEnum.ApprovedPremisesOrBody => Cdms.Model.Ipaffs.IpaffsPurposeInternalMarketPurposeEnum.ApprovedPremisesOrBody,
    Cdms.Types.Ipaffs.IpaffsPurposeInternalMarketPurposeEnum.CompanionAnimalNotForResaleOrRehoming => Cdms.Model.Ipaffs.IpaffsPurposeInternalMarketPurposeEnum.CompanionAnimalNotForResaleOrRehoming,
    Cdms.Types.Ipaffs.IpaffsPurposeInternalMarketPurposeEnum.Production => Cdms.Model.Ipaffs.IpaffsPurposeInternalMarketPurposeEnum.Production,
    Cdms.Types.Ipaffs.IpaffsPurposeInternalMarketPurposeEnum.Slaughter => Cdms.Model.Ipaffs.IpaffsPurposeInternalMarketPurposeEnum.Slaughter,
    Cdms.Types.Ipaffs.IpaffsPurposeInternalMarketPurposeEnum.Fattening => Cdms.Model.Ipaffs.IpaffsPurposeInternalMarketPurposeEnum.Fattening,
    Cdms.Types.Ipaffs.IpaffsPurposeInternalMarketPurposeEnum.GameRestocking => Cdms.Model.Ipaffs.IpaffsPurposeInternalMarketPurposeEnum.GameRestocking,
    Cdms.Types.Ipaffs.IpaffsPurposeInternalMarketPurposeEnum.RegisteredHorses => Cdms.Model.Ipaffs.IpaffsPurposeInternalMarketPurposeEnum.RegisteredHorses,
     
};
}
        

}


