//------------------------------------------------------------------------------
// <auto-generated>
    //     This code was generated from a template.
    //
    //     Manual changes to this file may cause unexpected behavior in your application.
    //     Manual changes to this file will be overwritten if the code is regenerated.
    // </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Cdms.Types.Ipaffs.Mapping;

public static class IpaffsTemperatureEnumMapper
{
public static Cdms.Model.Ipaffs.IpaffsTemperatureEnum? Map(Cdms.Types.Ipaffs.IpaffsTemperatureEnum? from)
{
if(from == null)
{
return default!;
}
return from switch
{
Cdms.Types.Ipaffs.IpaffsTemperatureEnum.Ambient => Cdms.Model.Ipaffs.IpaffsTemperatureEnum.Ambient,
    Cdms.Types.Ipaffs.IpaffsTemperatureEnum.Chilled => Cdms.Model.Ipaffs.IpaffsTemperatureEnum.Chilled,
    Cdms.Types.Ipaffs.IpaffsTemperatureEnum.Frozen => Cdms.Model.Ipaffs.IpaffsTemperatureEnum.Frozen,
     
};
}
        

}


