//------------------------------------------------------------------------------
// <auto-generated>
	//     This code was generated from a template.
	//
	//     Manual changes to this file may cause unexpected behavior in your application.
	//     Manual changes to this file will be overwritten if the code is regenerated.
	//
//</auto-generated>
//------------------------------------------------------------------------------
#nullable enable


namespace Cdms.Types.Ipaffs.Mapping;

public static class IpaffsChedppNotAcceptableReasonMapper
{
	public static Cdms.Model.Ipaffs.IpaffsChedppNotAcceptableReason Map(Cdms.Types.Ipaffs.IpaffsChedppNotAcceptableReason from)
	{
	if(from is null)
	{
		return default!;
	}
		var to = new Cdms.Model.Ipaffs.IpaffsChedppNotAcceptableReason ();
to.Reason = IpaffsChedppNotAcceptableReasonReasonEnumMapper.Map(from?.Reason);
                to.CommodityOrPackage = IpaffsChedppNotAcceptableReasonCommodityOrPackageEnumMapper.Map(from?.CommodityOrPackage);
                	return to;
	}
}

