//------------------------------------------------------------------------------
// <auto-generated>
    //     This code was generated from a template.
    //
    //     Manual changes to this file may cause unexpected behavior in your application.
    //     Manual changes to this file will be overwritten if the code is regenerated.
    // </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Cdms.Types.Ipaffs.Mapping;

public static class IpaffsApplicantConservationOfSampleEnumMapper
{
public static Cdms.Model.Ipaffs.IpaffsApplicantConservationOfSampleEnum? Map(Cdms.Types.Ipaffs.IpaffsApplicantConservationOfSampleEnum? from)
{
if(from == null)
{
return default!;
}
return from switch
{
Cdms.Types.Ipaffs.IpaffsApplicantConservationOfSampleEnum.Ambient => Cdms.Model.Ipaffs.IpaffsApplicantConservationOfSampleEnum.Ambient,
    Cdms.Types.Ipaffs.IpaffsApplicantConservationOfSampleEnum.Chilled => Cdms.Model.Ipaffs.IpaffsApplicantConservationOfSampleEnum.Chilled,
    Cdms.Types.Ipaffs.IpaffsApplicantConservationOfSampleEnum.Frozen => Cdms.Model.Ipaffs.IpaffsApplicantConservationOfSampleEnum.Frozen,
     
};
}
        

}


