//------------------------------------------------------------------------------
// <auto-generated>
    //     This code was generated from a template.
    //
    //     Manual changes to this file may cause unexpected behavior in your application.
    //     Manual changes to this file will be overwritten if the code is regenerated.
    // </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Cdms.Types.Ipaffs.Mapping;

public static class IpaffsDetailsOnReExportTransportTypeEnumMapper
{
public static Cdms.Model.Ipaffs.IpaffsDetailsOnReExportTransportTypeEnum? Map(Cdms.Types.Ipaffs.IpaffsDetailsOnReExportTransportTypeEnum? from)
{
if(from == null)
{
return default!;
}
return from switch
{
Cdms.Types.Ipaffs.IpaffsDetailsOnReExportTransportTypeEnum.Rail => Cdms.Model.Ipaffs.IpaffsDetailsOnReExportTransportTypeEnum.Rail,
    Cdms.Types.Ipaffs.IpaffsDetailsOnReExportTransportTypeEnum.Plane => Cdms.Model.Ipaffs.IpaffsDetailsOnReExportTransportTypeEnum.Plane,
    Cdms.Types.Ipaffs.IpaffsDetailsOnReExportTransportTypeEnum.Ship => Cdms.Model.Ipaffs.IpaffsDetailsOnReExportTransportTypeEnum.Ship,
    Cdms.Types.Ipaffs.IpaffsDetailsOnReExportTransportTypeEnum.Road => Cdms.Model.Ipaffs.IpaffsDetailsOnReExportTransportTypeEnum.Road,
    Cdms.Types.Ipaffs.IpaffsDetailsOnReExportTransportTypeEnum.Other => Cdms.Model.Ipaffs.IpaffsDetailsOnReExportTransportTypeEnum.Other,
    Cdms.Types.Ipaffs.IpaffsDetailsOnReExportTransportTypeEnum.CShipRoad => Cdms.Model.Ipaffs.IpaffsDetailsOnReExportTransportTypeEnum.CShipRoad,
    Cdms.Types.Ipaffs.IpaffsDetailsOnReExportTransportTypeEnum.CShipRail => Cdms.Model.Ipaffs.IpaffsDetailsOnReExportTransportTypeEnum.CShipRail,
     
};
}
        

}


