//------------------------------------------------------------------------------
// <auto-generated>
    //     This code was generated from a template.
    //
    //     Manual changes to this file may cause unexpected behavior in your application.
    //     Manual changes to this file will be overwritten if the code is regenerated.
    // </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Cdms.Types.Ipaffs.Mapping;

public static class IpaffsCommodityRiskResultPhsiDecisionEnumMapper
{
public static Cdms.Model.Ipaffs.IpaffsCommodityRiskResultPhsiDecisionEnum? Map(Cdms.Types.Ipaffs.IpaffsCommodityRiskResultPhsiDecisionEnum? from)
{
if(from == null)
{
return default!;
}
return from switch
{
Cdms.Types.Ipaffs.IpaffsCommodityRiskResultPhsiDecisionEnum.Required => Cdms.Model.Ipaffs.IpaffsCommodityRiskResultPhsiDecisionEnum.Required,
    Cdms.Types.Ipaffs.IpaffsCommodityRiskResultPhsiDecisionEnum.Notrequired => Cdms.Model.Ipaffs.IpaffsCommodityRiskResultPhsiDecisionEnum.Notrequired,
     
};
}
        

}


