//------------------------------------------------------------------------------
// <auto-generated>
    //     This code was generated from a template.
    //
    //     Manual changes to this file may cause unexpected behavior in your application.
    //     Manual changes to this file will be overwritten if the code is regenerated.
    // </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Cdms.Types.Ipaffs.Mapping;

public static class IpaffsControlConsignmentLeaveEnumMapper
{
public static Cdms.Model.Ipaffs.IpaffsControlConsignmentLeaveEnum? Map(Cdms.Types.Ipaffs.IpaffsControlConsignmentLeaveEnum? from)
{
if(from == null)
{
return default!;
}
return from switch
{
Cdms.Types.Ipaffs.IpaffsControlConsignmentLeaveEnum.Yes => Cdms.Model.Ipaffs.IpaffsControlConsignmentLeaveEnum.Yes,
    Cdms.Types.Ipaffs.IpaffsControlConsignmentLeaveEnum.No => Cdms.Model.Ipaffs.IpaffsControlConsignmentLeaveEnum.No,
    Cdms.Types.Ipaffs.IpaffsControlConsignmentLeaveEnum.ItHasBeenDestroyed => Cdms.Model.Ipaffs.IpaffsControlConsignmentLeaveEnum.ItHasBeenDestroyed,
     
};
}
        

}


