//------------------------------------------------------------------------------
// <auto-generated>
    //     This code was generated from a template.
    //
    //     Manual changes to this file may cause unexpected behavior in your application.
    //     Manual changes to this file will be overwritten if the code is regenerated.
    // </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Cdms.Types.Ipaffs.Mapping;

public static class IpaffsPurposePurposeGroupEnumMapper
{
public static Cdms.Model.Ipaffs.IpaffsPurposePurposeGroupEnum? Map(Cdms.Types.Ipaffs.IpaffsPurposePurposeGroupEnum? from)
{
if(from == null)
{
return default!;
}
return from switch
{
Cdms.Types.Ipaffs.IpaffsPurposePurposeGroupEnum.ForImport => Cdms.Model.Ipaffs.IpaffsPurposePurposeGroupEnum.ForImport,
    Cdms.Types.Ipaffs.IpaffsPurposePurposeGroupEnum.ForNONConformingConsignments => Cdms.Model.Ipaffs.IpaffsPurposePurposeGroupEnum.ForNONConformingConsignments,
    Cdms.Types.Ipaffs.IpaffsPurposePurposeGroupEnum.ForTranshipmentTo => Cdms.Model.Ipaffs.IpaffsPurposePurposeGroupEnum.ForTranshipmentTo,
    Cdms.Types.Ipaffs.IpaffsPurposePurposeGroupEnum.ForTransitTo3rdCountry => Cdms.Model.Ipaffs.IpaffsPurposePurposeGroupEnum.ForTransitTo3rdCountry,
    Cdms.Types.Ipaffs.IpaffsPurposePurposeGroupEnum.ForReImport => Cdms.Model.Ipaffs.IpaffsPurposePurposeGroupEnum.ForReImport,
    Cdms.Types.Ipaffs.IpaffsPurposePurposeGroupEnum.ForPrivateImport => Cdms.Model.Ipaffs.IpaffsPurposePurposeGroupEnum.ForPrivateImport,
    Cdms.Types.Ipaffs.IpaffsPurposePurposeGroupEnum.ForTransferTo => Cdms.Model.Ipaffs.IpaffsPurposePurposeGroupEnum.ForTransferTo,
    Cdms.Types.Ipaffs.IpaffsPurposePurposeGroupEnum.ForImportReConformityCheck => Cdms.Model.Ipaffs.IpaffsPurposePurposeGroupEnum.ForImportReConformityCheck,
     
};
}
        

}


