//------------------------------------------------------------------------------
// <auto-generated>
    //     This code was generated from a template.
    //
    //     Manual changes to this file may cause unexpected behavior in your application.
    //     Manual changes to this file will be overwritten if the code is regenerated.
    // </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Cdms.Types.Ipaffs.Mapping;

public static class IpaffsEconomicOperatorStatusEnumMapper
{
public static Cdms.Model.Ipaffs.IpaffsEconomicOperatorStatusEnum? Map(Cdms.Types.Ipaffs.IpaffsEconomicOperatorStatusEnum? from)
{
if(from == null)
{
return default!;
}
return from switch
{
Cdms.Types.Ipaffs.IpaffsEconomicOperatorStatusEnum.Approved => Cdms.Model.Ipaffs.IpaffsEconomicOperatorStatusEnum.Approved,
    Cdms.Types.Ipaffs.IpaffsEconomicOperatorStatusEnum.Nonapproved => Cdms.Model.Ipaffs.IpaffsEconomicOperatorStatusEnum.Nonapproved,
    Cdms.Types.Ipaffs.IpaffsEconomicOperatorStatusEnum.Suspended => Cdms.Model.Ipaffs.IpaffsEconomicOperatorStatusEnum.Suspended,
     
};
}
        

}


