//------------------------------------------------------------------------------
// <auto-generated>
	//     This code was generated from a template.
	//
	//     Manual changes to this file may cause unexpected behavior in your application.
	//     Manual changes to this file will be overwritten if the code is regenerated.
	//
//</auto-generated>
//------------------------------------------------------------------------------
#nullable enable


namespace Cdms.Types.Ipaffs.Mapping;

public static class IpaffsAccompanyingDocumentMapper
{
	public static Cdms.Model.Ipaffs.IpaffsAccompanyingDocument Map(Cdms.Types.Ipaffs.IpaffsAccompanyingDocument from)
	{
	if(from is null)
	{
		return default!;
	}
		var to = new Cdms.Model.Ipaffs.IpaffsAccompanyingDocument ();
to.DocumentType = IpaffsAccompanyingDocumentDocumentTypeEnumMapper.Map(from?.DocumentType);
                to.DocumentReference = from.DocumentReference;
            to.DocumentIssueDate = from.DocumentIssueDate;
            to.AttachmentId = from.AttachmentId;
            to.AttachmentFilename = from.AttachmentFilename;
            to.AttachmentContentType = from.AttachmentContentType;
            to.UploadUserId = from.UploadUserId;
            to.UploadOrganisationId = from.UploadOrganisationId;
            to.ExternalReference = IpaffsExternalReferenceMapper.Map(from?.ExternalReference);
                	return to;
	}
}

