//------------------------------------------------------------------------------
// <auto-generated>
    //     This code was generated from a template.
    //
    //     Manual changes to this file may cause unexpected behavior in your application.
    //     Manual changes to this file will be overwritten if the code is regenerated.
    // </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Cdms.Types.Ipaffs.Mapping;

public static class IpaffsPurposeForImportOrAdmissionEnumMapper
{
public static Cdms.Model.Ipaffs.IpaffsPurposeForImportOrAdmissionEnum? Map(Cdms.Types.Ipaffs.IpaffsPurposeForImportOrAdmissionEnum? from)
{
if(from == null)
{
return default!;
}
return from switch
{
Cdms.Types.Ipaffs.IpaffsPurposeForImportOrAdmissionEnum.DefinitiveImport => Cdms.Model.Ipaffs.IpaffsPurposeForImportOrAdmissionEnum.DefinitiveImport,
    Cdms.Types.Ipaffs.IpaffsPurposeForImportOrAdmissionEnum.HorsesReEntry => Cdms.Model.Ipaffs.IpaffsPurposeForImportOrAdmissionEnum.HorsesReEntry,
    Cdms.Types.Ipaffs.IpaffsPurposeForImportOrAdmissionEnum.TemporaryAdmissionHorses => Cdms.Model.Ipaffs.IpaffsPurposeForImportOrAdmissionEnum.TemporaryAdmissionHorses,
     
};
}
        

}


