//------------------------------------------------------------------------------
// <auto-generated>
    //     This code was generated from a template.
    //
    //     Manual changes to this file may cause unexpected behavior in your application.
    //     Manual changes to this file will be overwritten if the code is regenerated.
    // </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Cdms.Types.Ipaffs.Mapping;

public static class IpaffsDecisionFreeCirculationPurposeEnumMapper
{
public static Cdms.Model.Ipaffs.IpaffsDecisionFreeCirculationPurposeEnum? Map(Cdms.Types.Ipaffs.IpaffsDecisionFreeCirculationPurposeEnum? from)
{
if(from == null)
{
return default!;
}
return from switch
{
Cdms.Types.Ipaffs.IpaffsDecisionFreeCirculationPurposeEnum.AnimalFeedingStuff => Cdms.Model.Ipaffs.IpaffsDecisionFreeCirculationPurposeEnum.AnimalFeedingStuff,
    Cdms.Types.Ipaffs.IpaffsDecisionFreeCirculationPurposeEnum.HumanConsumption => Cdms.Model.Ipaffs.IpaffsDecisionFreeCirculationPurposeEnum.HumanConsumption,
    Cdms.Types.Ipaffs.IpaffsDecisionFreeCirculationPurposeEnum.PharmaceuticalUse => Cdms.Model.Ipaffs.IpaffsDecisionFreeCirculationPurposeEnum.PharmaceuticalUse,
    Cdms.Types.Ipaffs.IpaffsDecisionFreeCirculationPurposeEnum.TechnicalUse => Cdms.Model.Ipaffs.IpaffsDecisionFreeCirculationPurposeEnum.TechnicalUse,
    Cdms.Types.Ipaffs.IpaffsDecisionFreeCirculationPurposeEnum.FurtherProcess => Cdms.Model.Ipaffs.IpaffsDecisionFreeCirculationPurposeEnum.FurtherProcess,
    Cdms.Types.Ipaffs.IpaffsDecisionFreeCirculationPurposeEnum.Other => Cdms.Model.Ipaffs.IpaffsDecisionFreeCirculationPurposeEnum.Other,
     
};
}
        

}


