//------------------------------------------------------------------------------
// <auto-generated>
    //     This code was generated from a template.
    //
    //     Manual changes to this file may cause unexpected behavior in your application.
    //     Manual changes to this file will be overwritten if the code is regenerated.
    // </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Cdms.Types.Ipaffs.Mapping;

public static class IpaffsChedppNotAcceptableReasonCommodityOrPackageEnumMapper
{
public static Cdms.Model.Ipaffs.IpaffsChedppNotAcceptableReasonCommodityOrPackageEnum? Map(Cdms.Types.Ipaffs.IpaffsChedppNotAcceptableReasonCommodityOrPackageEnum? from)
{
if(from == null)
{
return default!;
}
return from switch
{
Cdms.Types.Ipaffs.IpaffsChedppNotAcceptableReasonCommodityOrPackageEnum.C => Cdms.Model.Ipaffs.IpaffsChedppNotAcceptableReasonCommodityOrPackageEnum.C,
    Cdms.Types.Ipaffs.IpaffsChedppNotAcceptableReasonCommodityOrPackageEnum.P => Cdms.Model.Ipaffs.IpaffsChedppNotAcceptableReasonCommodityOrPackageEnum.P,
    Cdms.Types.Ipaffs.IpaffsChedppNotAcceptableReasonCommodityOrPackageEnum.Cp => Cdms.Model.Ipaffs.IpaffsChedppNotAcceptableReasonCommodityOrPackageEnum.Cp,
     
};
}
        

}


