//------------------------------------------------------------------------------
// <auto-generated>
    //     This code was generated from a template.
    //
    //     Manual changes to this file may cause unexpected behavior in your application.
    //     Manual changes to this file will be overwritten if the code is regenerated.
    // </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Cdms.Types.Ipaffs.Mapping;

public static class IpaffsExternalReferenceSystemEnumMapper
{
public static Cdms.Model.Ipaffs.IpaffsExternalReferenceSystemEnum? Map(Cdms.Types.Ipaffs.IpaffsExternalReferenceSystemEnum? from)
{
if(from == null)
{
return default!;
}
return from switch
{
Cdms.Types.Ipaffs.IpaffsExternalReferenceSystemEnum.Ecert => Cdms.Model.Ipaffs.IpaffsExternalReferenceSystemEnum.Ecert,
    Cdms.Types.Ipaffs.IpaffsExternalReferenceSystemEnum.Ephyto => Cdms.Model.Ipaffs.IpaffsExternalReferenceSystemEnum.Ephyto,
    Cdms.Types.Ipaffs.IpaffsExternalReferenceSystemEnum.Enotification => Cdms.Model.Ipaffs.IpaffsExternalReferenceSystemEnum.Enotification,
    Cdms.Types.Ipaffs.IpaffsExternalReferenceSystemEnum.Ncts => Cdms.Model.Ipaffs.IpaffsExternalReferenceSystemEnum.Ncts,
     
};
}
        

}


