//------------------------------------------------------------------------------
// <auto-generated>
    //     This code was generated from a template.
    //
    //     Manual changes to this file may cause unexpected behavior in your application.
    //     Manual changes to this file will be overwritten if the code is regenerated.
    // </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Cdms.Types.Ipaffs.Mapping;

public static class IpaffsPurposeForNonConformingEnumMapper
{
public static Cdms.Model.Ipaffs.IpaffsPurposeForNonConformingEnum? Map(Cdms.Types.Ipaffs.IpaffsPurposeForNonConformingEnum? from)
{
if(from == null)
{
return default!;
}
return from switch
{
Cdms.Types.Ipaffs.IpaffsPurposeForNonConformingEnum.CustomsWarehouse => Cdms.Model.Ipaffs.IpaffsPurposeForNonConformingEnum.CustomsWarehouse,
    Cdms.Types.Ipaffs.IpaffsPurposeForNonConformingEnum.FreeZoneOrFreeWarehouse => Cdms.Model.Ipaffs.IpaffsPurposeForNonConformingEnum.FreeZoneOrFreeWarehouse,
    Cdms.Types.Ipaffs.IpaffsPurposeForNonConformingEnum.ShipSupplier => Cdms.Model.Ipaffs.IpaffsPurposeForNonConformingEnum.ShipSupplier,
    Cdms.Types.Ipaffs.IpaffsPurposeForNonConformingEnum.Ship => Cdms.Model.Ipaffs.IpaffsPurposeForNonConformingEnum.Ship,
     
};
}
        

}


