//------------------------------------------------------------------------------
// <auto-generated>
    //     This code was generated from a template.
    //
    //     Manual changes to this file may cause unexpected behavior in your application.
    //     Manual changes to this file will be overwritten if the code is regenerated.
    // </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Cdms.Types.Ipaffs.Mapping;

public static class IpaffsCommodityRiskResultPhsiClassificationEnumMapper
{
public static Cdms.Model.Ipaffs.IpaffsCommodityRiskResultPhsiClassificationEnum? Map(Cdms.Types.Ipaffs.IpaffsCommodityRiskResultPhsiClassificationEnum? from)
{
if(from == null)
{
return default!;
}
return from switch
{
Cdms.Types.Ipaffs.IpaffsCommodityRiskResultPhsiClassificationEnum.Mandatory => Cdms.Model.Ipaffs.IpaffsCommodityRiskResultPhsiClassificationEnum.Mandatory,
    Cdms.Types.Ipaffs.IpaffsCommodityRiskResultPhsiClassificationEnum.Reduced => Cdms.Model.Ipaffs.IpaffsCommodityRiskResultPhsiClassificationEnum.Reduced,
    Cdms.Types.Ipaffs.IpaffsCommodityRiskResultPhsiClassificationEnum.Controlled => Cdms.Model.Ipaffs.IpaffsCommodityRiskResultPhsiClassificationEnum.Controlled,
     
};
}
        

}


