//------------------------------------------------------------------------------
// <auto-generated>
    //     This code was generated from a template.
    //
    //     Manual changes to this file may cause unexpected behavior in your application.
    //     Manual changes to this file will be overwritten if the code is regenerated.
    // </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Cdms.Types.Ipaffs.Mapping;

public static class IpaffsPartOneTypeOfImpEnumMapper
{
public static Cdms.Model.Ipaffs.IpaffsPartOneTypeOfImpEnum? Map(Cdms.Types.Ipaffs.IpaffsPartOneTypeOfImpEnum? from)
{
if(from == null)
{
return default!;
}
return from switch
{
Cdms.Types.Ipaffs.IpaffsPartOneTypeOfImpEnum.A => Cdms.Model.Ipaffs.IpaffsPartOneTypeOfImpEnum.A,
    Cdms.Types.Ipaffs.IpaffsPartOneTypeOfImpEnum.P => Cdms.Model.Ipaffs.IpaffsPartOneTypeOfImpEnum.P,
    Cdms.Types.Ipaffs.IpaffsPartOneTypeOfImpEnum.D => Cdms.Model.Ipaffs.IpaffsPartOneTypeOfImpEnum.D,
     
};
}
        

}


