//------------------------------------------------------------------------------
// <auto-generated>
    //     This code was generated from a template.
    //
    //     Manual changes to this file may cause unexpected behavior in your application.
    //     Manual changes to this file will be overwritten if the code is regenerated.
    // </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Cdms.Types.Ipaffs.Mapping;

public static class IpaffsCommodityRiskResultRiskDecisionEnumMapper
{
public static Cdms.Model.Ipaffs.IpaffsCommodityRiskResultRiskDecisionEnum? Map(Cdms.Types.Ipaffs.IpaffsCommodityRiskResultRiskDecisionEnum? from)
{
if(from == null)
{
return default!;
}
return from switch
{
Cdms.Types.Ipaffs.IpaffsCommodityRiskResultRiskDecisionEnum.Required => Cdms.Model.Ipaffs.IpaffsCommodityRiskResultRiskDecisionEnum.Required,
    Cdms.Types.Ipaffs.IpaffsCommodityRiskResultRiskDecisionEnum.Notrequired => Cdms.Model.Ipaffs.IpaffsCommodityRiskResultRiskDecisionEnum.Notrequired,
    Cdms.Types.Ipaffs.IpaffsCommodityRiskResultRiskDecisionEnum.Inconclusive => Cdms.Model.Ipaffs.IpaffsCommodityRiskResultRiskDecisionEnum.Inconclusive,
    Cdms.Types.Ipaffs.IpaffsCommodityRiskResultRiskDecisionEnum.ReenforcedCheck => Cdms.Model.Ipaffs.IpaffsCommodityRiskResultRiskDecisionEnum.ReenforcedCheck,
     
};
}
        

}


