//------------------------------------------------------------------------------
// <auto-generated>
	//     This code was generated from a template.
	//
	//     Manual changes to this file may cause unexpected behavior in your application.
	//     Manual changes to this file will be overwritten if the code is regenerated.
	//
//</auto-generated>
//------------------------------------------------------------------------------
#nullable enable


namespace Cdms.Types.Ipaffs.Mapping;

public static class IpaffsCatchCertificatesMapper
{
	public static Cdms.Model.Ipaffs.IpaffsCatchCertificates Map(Cdms.Types.Ipaffs.IpaffsCatchCertificates from)
	{
	if(from is null)
	{
		return default!;
	}
		var to = new Cdms.Model.Ipaffs.IpaffsCatchCertificates ();
to.CertificateNumber = from.CertificateNumber;
            to.Weight = from.Weight;
            	return to;
	}
}

