//------------------------------------------------------------------------------
// <auto-generated>
    //     This code was generated from a template.
    //
    //     Manual changes to this file may cause unexpected behavior in your application.
    //     Manual changes to this file will be overwritten if the code is regenerated.
    // </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Cdms.Types.Ipaffs.Mapping;

public static class IpaffsDecisionDecisionEnumMapper
{
public static Cdms.Model.Ipaffs.IpaffsDecisionDecisionEnum? Map(Cdms.Types.Ipaffs.IpaffsDecisionDecisionEnum? from)
{
if(from == null)
{
return default!;
}
return from switch
{
Cdms.Types.Ipaffs.IpaffsDecisionDecisionEnum.NonAcceptable => Cdms.Model.Ipaffs.IpaffsDecisionDecisionEnum.NonAcceptable,
    Cdms.Types.Ipaffs.IpaffsDecisionDecisionEnum.AcceptableForInternalMarket => Cdms.Model.Ipaffs.IpaffsDecisionDecisionEnum.AcceptableForInternalMarket,
    Cdms.Types.Ipaffs.IpaffsDecisionDecisionEnum.AcceptableIfChanneled => Cdms.Model.Ipaffs.IpaffsDecisionDecisionEnum.AcceptableIfChanneled,
    Cdms.Types.Ipaffs.IpaffsDecisionDecisionEnum.AcceptableForTranshipment => Cdms.Model.Ipaffs.IpaffsDecisionDecisionEnum.AcceptableForTranshipment,
    Cdms.Types.Ipaffs.IpaffsDecisionDecisionEnum.AcceptableForTransit => Cdms.Model.Ipaffs.IpaffsDecisionDecisionEnum.AcceptableForTransit,
    Cdms.Types.Ipaffs.IpaffsDecisionDecisionEnum.AcceptableForTemporaryImport => Cdms.Model.Ipaffs.IpaffsDecisionDecisionEnum.AcceptableForTemporaryImport,
    Cdms.Types.Ipaffs.IpaffsDecisionDecisionEnum.AcceptableForSpecificWarehouse => Cdms.Model.Ipaffs.IpaffsDecisionDecisionEnum.AcceptableForSpecificWarehouse,
    Cdms.Types.Ipaffs.IpaffsDecisionDecisionEnum.AcceptableForPrivateImport => Cdms.Model.Ipaffs.IpaffsDecisionDecisionEnum.AcceptableForPrivateImport,
    Cdms.Types.Ipaffs.IpaffsDecisionDecisionEnum.AcceptableForTransfer => Cdms.Model.Ipaffs.IpaffsDecisionDecisionEnum.AcceptableForTransfer,
    Cdms.Types.Ipaffs.IpaffsDecisionDecisionEnum.HorseReEntry => Cdms.Model.Ipaffs.IpaffsDecisionDecisionEnum.HorseReEntry,
     
};
}
        

}


