//------------------------------------------------------------------------------
// <auto-generated>
	//     This code was generated from a template.
	//
	//     Manual changes to this file may cause unexpected behavior in your application.
	//     Manual changes to this file will be overwritten if the code is regenerated.
	//
//</auto-generated>
//------------------------------------------------------------------------------
#nullable enable


namespace Cdms.Types.Ipaffs.Mapping;

public static class IpaffsInspectionOverrideMapper
{
	public static Cdms.Model.Ipaffs.IpaffsInspectionOverride Map(Cdms.Types.Ipaffs.IpaffsInspectionOverride from)
	{
	if(from is null)
	{
		return default!;
	}
		var to = new Cdms.Model.Ipaffs.IpaffsInspectionOverride ();
to.OriginalDecision = from.OriginalDecision;
            to.OverriddenOn = from.OverriddenOn;
            to.OverriddenBy = IpaffsUserInformationMapper.Map(from?.OverriddenBy);
                	return to;
	}
}

