//------------------------------------------------------------------------------
// <auto-generated>
    //     This code was generated from a template.
    //
    //     Manual changes to this file may cause unexpected behavior in your application.
    //     Manual changes to this file will be overwritten if the code is regenerated.
    // </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Cdms.Types.Ipaffs.Mapping;

public static class IpaffsChedppNotAcceptableReasonReasonEnumMapper
{
public static Cdms.Model.Ipaffs.IpaffsChedppNotAcceptableReasonReasonEnum? Map(Cdms.Types.Ipaffs.IpaffsChedppNotAcceptableReasonReasonEnum? from)
{
if(from == null)
{
return default!;
}
return from switch
{
Cdms.Types.Ipaffs.IpaffsChedppNotAcceptableReasonReasonEnum.DocPhmdm => Cdms.Model.Ipaffs.IpaffsChedppNotAcceptableReasonReasonEnum.DocPhmdm,
    Cdms.Types.Ipaffs.IpaffsChedppNotAcceptableReasonReasonEnum.DocPhmdii => Cdms.Model.Ipaffs.IpaffsChedppNotAcceptableReasonReasonEnum.DocPhmdii,
    Cdms.Types.Ipaffs.IpaffsChedppNotAcceptableReasonReasonEnum.DocPa => Cdms.Model.Ipaffs.IpaffsChedppNotAcceptableReasonReasonEnum.DocPa,
    Cdms.Types.Ipaffs.IpaffsChedppNotAcceptableReasonReasonEnum.DocPic => Cdms.Model.Ipaffs.IpaffsChedppNotAcceptableReasonReasonEnum.DocPic,
    Cdms.Types.Ipaffs.IpaffsChedppNotAcceptableReasonReasonEnum.DocPill => Cdms.Model.Ipaffs.IpaffsChedppNotAcceptableReasonReasonEnum.DocPill,
    Cdms.Types.Ipaffs.IpaffsChedppNotAcceptableReasonReasonEnum.DocPed => Cdms.Model.Ipaffs.IpaffsChedppNotAcceptableReasonReasonEnum.DocPed,
    Cdms.Types.Ipaffs.IpaffsChedppNotAcceptableReasonReasonEnum.DocPmod => Cdms.Model.Ipaffs.IpaffsChedppNotAcceptableReasonReasonEnum.DocPmod,
    Cdms.Types.Ipaffs.IpaffsChedppNotAcceptableReasonReasonEnum.DocPfi => Cdms.Model.Ipaffs.IpaffsChedppNotAcceptableReasonReasonEnum.DocPfi,
    Cdms.Types.Ipaffs.IpaffsChedppNotAcceptableReasonReasonEnum.DocPnol => Cdms.Model.Ipaffs.IpaffsChedppNotAcceptableReasonReasonEnum.DocPnol,
    Cdms.Types.Ipaffs.IpaffsChedppNotAcceptableReasonReasonEnum.DocPcne => Cdms.Model.Ipaffs.IpaffsChedppNotAcceptableReasonReasonEnum.DocPcne,
    Cdms.Types.Ipaffs.IpaffsChedppNotAcceptableReasonReasonEnum.DocPadm => Cdms.Model.Ipaffs.IpaffsChedppNotAcceptableReasonReasonEnum.DocPadm,
    Cdms.Types.Ipaffs.IpaffsChedppNotAcceptableReasonReasonEnum.DocPadi => Cdms.Model.Ipaffs.IpaffsChedppNotAcceptableReasonReasonEnum.DocPadi,
    Cdms.Types.Ipaffs.IpaffsChedppNotAcceptableReasonReasonEnum.DocPpni => Cdms.Model.Ipaffs.IpaffsChedppNotAcceptableReasonReasonEnum.DocPpni,
    Cdms.Types.Ipaffs.IpaffsChedppNotAcceptableReasonReasonEnum.DocPf => Cdms.Model.Ipaffs.IpaffsChedppNotAcceptableReasonReasonEnum.DocPf,
    Cdms.Types.Ipaffs.IpaffsChedppNotAcceptableReasonReasonEnum.DocPo => Cdms.Model.Ipaffs.IpaffsChedppNotAcceptableReasonReasonEnum.DocPo,
    Cdms.Types.Ipaffs.IpaffsChedppNotAcceptableReasonReasonEnum.DocNcevd => Cdms.Model.Ipaffs.IpaffsChedppNotAcceptableReasonReasonEnum.DocNcevd,
    Cdms.Types.Ipaffs.IpaffsChedppNotAcceptableReasonReasonEnum.DocNcpqefi => Cdms.Model.Ipaffs.IpaffsChedppNotAcceptableReasonReasonEnum.DocNcpqefi,
    Cdms.Types.Ipaffs.IpaffsChedppNotAcceptableReasonReasonEnum.DocNcpqebec => Cdms.Model.Ipaffs.IpaffsChedppNotAcceptableReasonReasonEnum.DocNcpqebec,
    Cdms.Types.Ipaffs.IpaffsChedppNotAcceptableReasonReasonEnum.DocNcts => Cdms.Model.Ipaffs.IpaffsChedppNotAcceptableReasonReasonEnum.DocNcts,
    Cdms.Types.Ipaffs.IpaffsChedppNotAcceptableReasonReasonEnum.DocNco => Cdms.Model.Ipaffs.IpaffsChedppNotAcceptableReasonReasonEnum.DocNco,
    Cdms.Types.Ipaffs.IpaffsChedppNotAcceptableReasonReasonEnum.DocOrii => Cdms.Model.Ipaffs.IpaffsChedppNotAcceptableReasonReasonEnum.DocOrii,
    Cdms.Types.Ipaffs.IpaffsChedppNotAcceptableReasonReasonEnum.DocOrsr => Cdms.Model.Ipaffs.IpaffsChedppNotAcceptableReasonReasonEnum.DocOrsr,
    Cdms.Types.Ipaffs.IpaffsChedppNotAcceptableReasonReasonEnum.OriOrrnu => Cdms.Model.Ipaffs.IpaffsChedppNotAcceptableReasonReasonEnum.OriOrrnu,
    Cdms.Types.Ipaffs.IpaffsChedppNotAcceptableReasonReasonEnum.PhyOrpp => Cdms.Model.Ipaffs.IpaffsChedppNotAcceptableReasonReasonEnum.PhyOrpp,
    Cdms.Types.Ipaffs.IpaffsChedppNotAcceptableReasonReasonEnum.PhyOrho => Cdms.Model.Ipaffs.IpaffsChedppNotAcceptableReasonReasonEnum.PhyOrho,
    Cdms.Types.Ipaffs.IpaffsChedppNotAcceptableReasonReasonEnum.PhyIs => Cdms.Model.Ipaffs.IpaffsChedppNotAcceptableReasonReasonEnum.PhyIs,
    Cdms.Types.Ipaffs.IpaffsChedppNotAcceptableReasonReasonEnum.PhyOrsr => Cdms.Model.Ipaffs.IpaffsChedppNotAcceptableReasonReasonEnum.PhyOrsr,
    Cdms.Types.Ipaffs.IpaffsChedppNotAcceptableReasonReasonEnum.OthCnl => Cdms.Model.Ipaffs.IpaffsChedppNotAcceptableReasonReasonEnum.OthCnl,
    Cdms.Types.Ipaffs.IpaffsChedppNotAcceptableReasonReasonEnum.OthO => Cdms.Model.Ipaffs.IpaffsChedppNotAcceptableReasonReasonEnum.OthO,
     
};
}
        

}


