//------------------------------------------------------------------------------
// <auto-generated>
    //     This code was generated from a template.
    //
    //     Manual changes to this file may cause unexpected behavior in your application.
    //     Manual changes to this file will be overwritten if the code is regenerated.
    // </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Cdms.Types.Ipaffs.Mapping;

public static class IpaffsCommoditiesCommodityIntendedForEnumMapper
{
public static Cdms.Model.Ipaffs.IpaffsCommoditiesCommodityIntendedForEnum? Map(Cdms.Types.Ipaffs.IpaffsCommoditiesCommodityIntendedForEnum? from)
{
if(from == null)
{
return default!;
}
return from switch
{
Cdms.Types.Ipaffs.IpaffsCommoditiesCommodityIntendedForEnum.Human => Cdms.Model.Ipaffs.IpaffsCommoditiesCommodityIntendedForEnum.Human,
    Cdms.Types.Ipaffs.IpaffsCommoditiesCommodityIntendedForEnum.Feedingstuff => Cdms.Model.Ipaffs.IpaffsCommoditiesCommodityIntendedForEnum.Feedingstuff,
    Cdms.Types.Ipaffs.IpaffsCommoditiesCommodityIntendedForEnum.Further => Cdms.Model.Ipaffs.IpaffsCommoditiesCommodityIntendedForEnum.Further,
    Cdms.Types.Ipaffs.IpaffsCommoditiesCommodityIntendedForEnum.Other => Cdms.Model.Ipaffs.IpaffsCommoditiesCommodityIntendedForEnum.Other,
     
};
}
        

}


