//------------------------------------------------------------------------------
// <auto-generated>
    //     This code was generated from a template.
    //
    //     Manual changes to this file may cause unexpected behavior in your application.
    //     Manual changes to this file will be overwritten if the code is regenerated.
    // </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Cdms.Types.Ipaffs.Mapping;

public static class IpaffsDecisionNotAcceptableActionDestructionReasonEnumMapper
{
public static Cdms.Model.Ipaffs.IpaffsDecisionNotAcceptableActionDestructionReasonEnum? Map(Cdms.Types.Ipaffs.IpaffsDecisionNotAcceptableActionDestructionReasonEnum? from)
{
if(from == null)
{
return default!;
}
return from switch
{
Cdms.Types.Ipaffs.IpaffsDecisionNotAcceptableActionDestructionReasonEnum.ContaminatedProducts => Cdms.Model.Ipaffs.IpaffsDecisionNotAcceptableActionDestructionReasonEnum.ContaminatedProducts,
    Cdms.Types.Ipaffs.IpaffsDecisionNotAcceptableActionDestructionReasonEnum.InterceptedPart => Cdms.Model.Ipaffs.IpaffsDecisionNotAcceptableActionDestructionReasonEnum.InterceptedPart,
    Cdms.Types.Ipaffs.IpaffsDecisionNotAcceptableActionDestructionReasonEnum.PackagingMaterial => Cdms.Model.Ipaffs.IpaffsDecisionNotAcceptableActionDestructionReasonEnum.PackagingMaterial,
    Cdms.Types.Ipaffs.IpaffsDecisionNotAcceptableActionDestructionReasonEnum.Other => Cdms.Model.Ipaffs.IpaffsDecisionNotAcceptableActionDestructionReasonEnum.Other,
     
};
}
        

}


