//------------------------------------------------------------------------------
// <auto-generated>
    //     This code was generated from a template.
    //
    //     Manual changes to this file may cause unexpected behavior in your application.
    //     Manual changes to this file will be overwritten if the code is regenerated.
    // </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Cdms.Types.Ipaffs.Mapping;

public static class IpaffsLaboratoryTestsTestReasonEnumMapper
{
public static Cdms.Model.Ipaffs.IpaffsLaboratoryTestsTestReasonEnum? Map(Cdms.Types.Ipaffs.IpaffsLaboratoryTestsTestReasonEnum? from)
{
if(from == null)
{
return default!;
}
return from switch
{
Cdms.Types.Ipaffs.IpaffsLaboratoryTestsTestReasonEnum.Random => Cdms.Model.Ipaffs.IpaffsLaboratoryTestsTestReasonEnum.Random,
    Cdms.Types.Ipaffs.IpaffsLaboratoryTestsTestReasonEnum.Suspicious => Cdms.Model.Ipaffs.IpaffsLaboratoryTestsTestReasonEnum.Suspicious,
    Cdms.Types.Ipaffs.IpaffsLaboratoryTestsTestReasonEnum.ReEnforced => Cdms.Model.Ipaffs.IpaffsLaboratoryTestsTestReasonEnum.ReEnforced,
    Cdms.Types.Ipaffs.IpaffsLaboratoryTestsTestReasonEnum.IntensifiedControls => Cdms.Model.Ipaffs.IpaffsLaboratoryTestsTestReasonEnum.IntensifiedControls,
    Cdms.Types.Ipaffs.IpaffsLaboratoryTestsTestReasonEnum.Required => Cdms.Model.Ipaffs.IpaffsLaboratoryTestsTestReasonEnum.Required,
    Cdms.Types.Ipaffs.IpaffsLaboratoryTestsTestReasonEnum.LatentInfectionSampling => Cdms.Model.Ipaffs.IpaffsLaboratoryTestsTestReasonEnum.LatentInfectionSampling,
     
};
}
        

}


