//------------------------------------------------------------------------------
// <auto-generated>
	//     This code was generated from a template.
	//
	//     Manual changes to this file may cause unexpected behavior in your application.
	//     Manual changes to this file will be overwritten if the code is regenerated.
	//
//</auto-generated>
//------------------------------------------------------------------------------
#nullable enable


namespace Cdms.Types.Ipaffs.Mapping;

public static class IpaffsApprovedEstablishmentMapper
{
	public static Cdms.Model.Ipaffs.IpaffsApprovedEstablishment Map(Cdms.Types.Ipaffs.IpaffsApprovedEstablishment from)
	{
	if(from is null)
	{
		return default!;
	}
		var to = new Cdms.Model.Ipaffs.IpaffsApprovedEstablishment ();
to.IpaffsId = from.IpaffsId;
            to.Name = from.Name;
            to.Country = from.Country;
            to.Types = from.Types;
            to.ApprovalNumber = from.ApprovalNumber;
            to.Section = from.Section;
            	return to;
	}
}

