//------------------------------------------------------------------------------
// <auto-generated>
    //     This code was generated from a template.
    //
    //     Manual changes to this file may cause unexpected behavior in your application.
    //     Manual changes to this file will be overwritten if the code is regenerated.
    // </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Cdms.Types.Ipaffs.Mapping;

public static class IpaffsImportNotificationTypeEnumMapper
{
public static Cdms.Model.Ipaffs.IpaffsImportNotificationTypeEnum? Map(Cdms.Types.Ipaffs.IpaffsImportNotificationTypeEnum? from)
{
if(from == null)
{
return default!;
}
return from switch
{
Cdms.Types.Ipaffs.IpaffsImportNotificationTypeEnum.Cveda => Cdms.Model.Ipaffs.IpaffsImportNotificationTypeEnum.Cveda,
    Cdms.Types.Ipaffs.IpaffsImportNotificationTypeEnum.Cvedp => Cdms.Model.Ipaffs.IpaffsImportNotificationTypeEnum.Cvedp,
    Cdms.Types.Ipaffs.IpaffsImportNotificationTypeEnum.Chedpp => Cdms.Model.Ipaffs.IpaffsImportNotificationTypeEnum.Chedpp,
    Cdms.Types.Ipaffs.IpaffsImportNotificationTypeEnum.Ced => Cdms.Model.Ipaffs.IpaffsImportNotificationTypeEnum.Ced,
    Cdms.Types.Ipaffs.IpaffsImportNotificationTypeEnum.Imp => Cdms.Model.Ipaffs.IpaffsImportNotificationTypeEnum.Imp,
     
};
}
        

}


