//------------------------------------------------------------------------------
// <auto-generated>
    //     This code was generated from a template.
    //
    //     Manual changes to this file may cause unexpected behavior in your application.
    //     Manual changes to this file will be overwritten if the code is regenerated.
    // </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Cdms.Types.Ipaffs.Mapping;

public static class IpaffsControlAuthorityIuuOptionEnumMapper
{
public static Cdms.Model.Ipaffs.IpaffsControlAuthorityIuuOptionEnum? Map(Cdms.Types.Ipaffs.IpaffsControlAuthorityIuuOptionEnum? from)
{
if(from == null)
{
return default!;
}
return from switch
{
Cdms.Types.Ipaffs.IpaffsControlAuthorityIuuOptionEnum.Iuuok => Cdms.Model.Ipaffs.IpaffsControlAuthorityIuuOptionEnum.Iuuok,
    Cdms.Types.Ipaffs.IpaffsControlAuthorityIuuOptionEnum.Iuuna => Cdms.Model.Ipaffs.IpaffsControlAuthorityIuuOptionEnum.Iuuna,
    Cdms.Types.Ipaffs.IpaffsControlAuthorityIuuOptionEnum.IUUNotCompliant => Cdms.Model.Ipaffs.IpaffsControlAuthorityIuuOptionEnum.IUUNotCompliant,
     
};
}
        

}


