//------------------------------------------------------------------------------
// <auto-generated>
    //     This code was generated from a template.
    //
    //     Manual changes to this file may cause unexpected behavior in your application.
    //     Manual changes to this file will be overwritten if the code is regenerated.
    // </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Cdms.Types.Ipaffs.Mapping;

public static class IpaffsFeedbackInformationAuthorityTypeEnumMapper
{
public static Cdms.Model.Ipaffs.IpaffsFeedbackInformationAuthorityTypeEnum? Map(Cdms.Types.Ipaffs.IpaffsFeedbackInformationAuthorityTypeEnum? from)
{
if(from == null)
{
return default!;
}
return from switch
{
Cdms.Types.Ipaffs.IpaffsFeedbackInformationAuthorityTypeEnum.Exitbip => Cdms.Model.Ipaffs.IpaffsFeedbackInformationAuthorityTypeEnum.Exitbip,
    Cdms.Types.Ipaffs.IpaffsFeedbackInformationAuthorityTypeEnum.Finalbip => Cdms.Model.Ipaffs.IpaffsFeedbackInformationAuthorityTypeEnum.Finalbip,
    Cdms.Types.Ipaffs.IpaffsFeedbackInformationAuthorityTypeEnum.Localvetunit => Cdms.Model.Ipaffs.IpaffsFeedbackInformationAuthorityTypeEnum.Localvetunit,
    Cdms.Types.Ipaffs.IpaffsFeedbackInformationAuthorityTypeEnum.Inspunit => Cdms.Model.Ipaffs.IpaffsFeedbackInformationAuthorityTypeEnum.Inspunit,
     
};
}
        

}


