//------------------------------------------------------------------------------
// <auto-generated>
    //     This code was generated from a template.
    //
    //     Manual changes to this file may cause unexpected behavior in your application.
    //     Manual changes to this file will be overwritten if the code is regenerated.
    // </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Cdms.Types.Ipaffs.Mapping;

public static class IpaffsPartThreeControlStatusEnumMapper
{
public static Cdms.Model.Ipaffs.IpaffsPartThreeControlStatusEnum? Map(Cdms.Types.Ipaffs.IpaffsPartThreeControlStatusEnum? from)
{
if(from == null)
{
return default!;
}
return from switch
{
Cdms.Types.Ipaffs.IpaffsPartThreeControlStatusEnum.Required => Cdms.Model.Ipaffs.IpaffsPartThreeControlStatusEnum.Required,
    Cdms.Types.Ipaffs.IpaffsPartThreeControlStatusEnum.Completed => Cdms.Model.Ipaffs.IpaffsPartThreeControlStatusEnum.Completed,
     
};
}
        

}


