//------------------------------------------------------------------------------
// <auto-generated>
    //     This code was generated from a template.
    //
    //     Manual changes to this file may cause unexpected behavior in your application.
    //     Manual changes to this file will be overwritten if the code is regenerated.
    // </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Cdms.Types.Ipaffs.Mapping;

public static class IpaffsUnitEnumMapper
{
public static Cdms.Model.Ipaffs.IpaffsUnitEnum? Map(Cdms.Types.Ipaffs.IpaffsUnitEnum? from)
{
if(from == null)
{
return default!;
}
return from switch
{
Cdms.Types.Ipaffs.IpaffsUnitEnum.Percent => Cdms.Model.Ipaffs.IpaffsUnitEnum.Percent,
    Cdms.Types.Ipaffs.IpaffsUnitEnum.Number => Cdms.Model.Ipaffs.IpaffsUnitEnum.Number,
     
};
}
        

}


