//------------------------------------------------------------------------------
// <auto-generated>
    //     This code was generated from a template.
    //
    //     Manual changes to this file may cause unexpected behavior in your application.
    //     Manual changes to this file will be overwritten if the code is regenerated.
    // </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Cdms.Types.Ipaffs.Mapping;

public static class IpaffsConsignmentCheckIdentityCheckNotDoneReasonEnumMapper
{
public static Cdms.Model.Ipaffs.IpaffsConsignmentCheckIdentityCheckNotDoneReasonEnum? Map(Cdms.Types.Ipaffs.IpaffsConsignmentCheckIdentityCheckNotDoneReasonEnum? from)
{
if(from == null)
{
return default!;
}
return from switch
{
Cdms.Types.Ipaffs.IpaffsConsignmentCheckIdentityCheckNotDoneReasonEnum.ReducedChecksRegime => Cdms.Model.Ipaffs.IpaffsConsignmentCheckIdentityCheckNotDoneReasonEnum.ReducedChecksRegime,
    Cdms.Types.Ipaffs.IpaffsConsignmentCheckIdentityCheckNotDoneReasonEnum.NotRequired => Cdms.Model.Ipaffs.IpaffsConsignmentCheckIdentityCheckNotDoneReasonEnum.NotRequired,
     
};
}
        

}


