//------------------------------------------------------------------------------
// <auto-generated>
    //     This code was generated from a template.
    //
    //     Manual changes to this file may cause unexpected behavior in your application.
    //     Manual changes to this file will be overwritten if the code is regenerated.
    // </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Cdms.Types.Ipaffs.Mapping;

public static class IpaffsDecisionNotAcceptableActionQuarantineImposedReasonEnumMapper
{
public static Cdms.Model.Ipaffs.IpaffsDecisionNotAcceptableActionQuarantineImposedReasonEnum? Map(Cdms.Types.Ipaffs.IpaffsDecisionNotAcceptableActionQuarantineImposedReasonEnum? from)
{
if(from == null)
{
return default!;
}
return from switch
{
Cdms.Types.Ipaffs.IpaffsDecisionNotAcceptableActionQuarantineImposedReasonEnum.ContaminatedProducts => Cdms.Model.Ipaffs.IpaffsDecisionNotAcceptableActionQuarantineImposedReasonEnum.ContaminatedProducts,
    Cdms.Types.Ipaffs.IpaffsDecisionNotAcceptableActionQuarantineImposedReasonEnum.InterceptedPart => Cdms.Model.Ipaffs.IpaffsDecisionNotAcceptableActionQuarantineImposedReasonEnum.InterceptedPart,
    Cdms.Types.Ipaffs.IpaffsDecisionNotAcceptableActionQuarantineImposedReasonEnum.PackagingMaterial => Cdms.Model.Ipaffs.IpaffsDecisionNotAcceptableActionQuarantineImposedReasonEnum.PackagingMaterial,
    Cdms.Types.Ipaffs.IpaffsDecisionNotAcceptableActionQuarantineImposedReasonEnum.Other => Cdms.Model.Ipaffs.IpaffsDecisionNotAcceptableActionQuarantineImposedReasonEnum.Other,
     
};
}
        

}


