//------------------------------------------------------------------------------
// <auto-generated>
	//     This code was generated from a template.
	//
	//     Manual changes to this file may cause unexpected behavior in your application.
	//     Manual changes to this file will be overwritten if the code is regenerated.
	//
//</auto-generated>
//------------------------------------------------------------------------------
#nullable enable


namespace Cdms.Types.Ipaffs.Mapping;

public static class IpaffsImpactOfTransportOnAnimalsMapper
{
	public static Cdms.Model.Ipaffs.IpaffsImpactOfTransportOnAnimals Map(Cdms.Types.Ipaffs.IpaffsImpactOfTransportOnAnimals from)
	{
	if(from is null)
	{
		return default!;
	}
		var to = new Cdms.Model.Ipaffs.IpaffsImpactOfTransportOnAnimals ();
to.NumberOfDeadAnimals = from.NumberOfDeadAnimals;
            to.NumberOfDeadAnimalsUnit = from.NumberOfDeadAnimalsUnit;
            to.NumberOfUnfitAnimals = from.NumberOfUnfitAnimals;
            to.NumberOfUnfitAnimalsUnit = from.NumberOfUnfitAnimalsUnit;
            to.NumberOfBirthOrAbortion = from.NumberOfBirthOrAbortion;
            	return to;
	}
}

