//------------------------------------------------------------------------------
// <auto-generated>
    //     This code was generated from a template.
    //
    //     Manual changes to this file may cause unexpected behavior in your application.
    //     Manual changes to this file will be overwritten if the code is regenerated.
    // </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Cdms.Types.Ipaffs.Mapping;

public static class IpaffsDecisionDefinitiveImportPurposeEnumMapper
{
public static Cdms.Model.Ipaffs.IpaffsDecisionDefinitiveImportPurposeEnum? Map(Cdms.Types.Ipaffs.IpaffsDecisionDefinitiveImportPurposeEnum? from)
{
if(from == null)
{
return default!;
}
return from switch
{
Cdms.Types.Ipaffs.IpaffsDecisionDefinitiveImportPurposeEnum.Slaughter => Cdms.Model.Ipaffs.IpaffsDecisionDefinitiveImportPurposeEnum.Slaughter,
    Cdms.Types.Ipaffs.IpaffsDecisionDefinitiveImportPurposeEnum.Approvedbodies => Cdms.Model.Ipaffs.IpaffsDecisionDefinitiveImportPurposeEnum.Approvedbodies,
    Cdms.Types.Ipaffs.IpaffsDecisionDefinitiveImportPurposeEnum.Quarantine => Cdms.Model.Ipaffs.IpaffsDecisionDefinitiveImportPurposeEnum.Quarantine,
     
};
}
        

}


