//------------------------------------------------------------------------------
// <auto-generated>
    //     This code was generated from a template.
    //
    //     Manual changes to this file may cause unexpected behavior in your application.
    //     Manual changes to this file will be overwritten if the code is regenerated.
    // </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Cdms.Types.Ipaffs.Mapping;

public static class IpaffsConsignmentCheckIdentityCheckTypeEnumMapper
{
public static Cdms.Model.Ipaffs.IpaffsConsignmentCheckIdentityCheckTypeEnum? Map(Cdms.Types.Ipaffs.IpaffsConsignmentCheckIdentityCheckTypeEnum? from)
{
if(from == null)
{
return default!;
}
return from switch
{
Cdms.Types.Ipaffs.IpaffsConsignmentCheckIdentityCheckTypeEnum.SealCheck => Cdms.Model.Ipaffs.IpaffsConsignmentCheckIdentityCheckTypeEnum.SealCheck,
    Cdms.Types.Ipaffs.IpaffsConsignmentCheckIdentityCheckTypeEnum.FullIdentityCheck => Cdms.Model.Ipaffs.IpaffsConsignmentCheckIdentityCheckTypeEnum.FullIdentityCheck,
    Cdms.Types.Ipaffs.IpaffsConsignmentCheckIdentityCheckTypeEnum.NotDone => Cdms.Model.Ipaffs.IpaffsConsignmentCheckIdentityCheckTypeEnum.NotDone,
     
};
}
        

}


