//------------------------------------------------------------------------------
// <auto-generated>
    //     This code was generated from a template.
    //
    //     Manual changes to this file may cause unexpected behavior in your application.
    //     Manual changes to this file will be overwritten if the code is regenerated.
    // </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Cdms.Types.Ipaffs.Mapping;

public static class IpaffsConsignmentCheckPhysicalCheckNotDoneReasonEnumMapper
{
public static Cdms.Model.Ipaffs.IpaffsConsignmentCheckPhysicalCheckNotDoneReasonEnum? Map(Cdms.Types.Ipaffs.IpaffsConsignmentCheckPhysicalCheckNotDoneReasonEnum? from)
{
if(from == null)
{
return default!;
}
return from switch
{
Cdms.Types.Ipaffs.IpaffsConsignmentCheckPhysicalCheckNotDoneReasonEnum.ReducedChecksRegime => Cdms.Model.Ipaffs.IpaffsConsignmentCheckPhysicalCheckNotDoneReasonEnum.ReducedChecksRegime,
    Cdms.Types.Ipaffs.IpaffsConsignmentCheckPhysicalCheckNotDoneReasonEnum.Other => Cdms.Model.Ipaffs.IpaffsConsignmentCheckPhysicalCheckNotDoneReasonEnum.Other,
     
};
}
        

}


