//------------------------------------------------------------------------------
// <auto-generated>
	//     This code was generated from a template.
	//
	//     Manual changes to this file may cause unexpected behavior in your application.
	//     Manual changes to this file will be overwritten if the code is regenerated.
	//
//</auto-generated>
//------------------------------------------------------------------------------
#nullable enable


namespace Cdms.Types.Ipaffs.Mapping;

public static class PartyMapper
{
	public static Cdms.Model.Ipaffs.Party Map(Cdms.Types.Ipaffs.Party from)
	{
	if(from is null)
	{
		return default!;
	}
		var to = new Cdms.Model.Ipaffs.Party ();
to.Id = from.Id;
            to.Name = from.Name;
            to.CompanyId = from.CompanyId;
            to.ContactId = from.ContactId;
            to.CompanyName = from.CompanyName;
            to.Addresses = from.Addresses;
            to.County = from.County;
            to.PostCode = from.PostCode;
            to.Country = from.Country;
            to.City = from.City;
            to.TracesId = from.TracesId;
            to.Type = PartyTypeEnumMapper.Map(from?.Type);
                to.ApprovalNumber = from.ApprovalNumber;
            to.Phone = from.Phone;
            to.Fax = from.Fax;
            to.Email = from.Email;
            	return to;
	}
}

