//------------------------------------------------------------------------------
// <auto-generated>
    //     This code was generated from a template.
    //
    //     Manual changes to this file may cause unexpected behavior in your application.
    //     Manual changes to this file will be overwritten if the code is regenerated.
    // </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Cdms.Types.Ipaffs.Mapping;

public static class PartyTypeEnumMapper
{
    public static Cdms.Model.Ipaffs.PartyTypeEnum? Map(Cdms.Types.Ipaffs.PartyTypeEnum? from)
    {
        if (from == null)
        {
            return default!;
        }

        return from switch
        {
            Cdms.Types.Ipaffs.PartyTypeEnum.CommercialTransporter => Cdms.Model.Ipaffs.PartyTypeEnum
                .CommercialTransporter,
            Cdms.Types.Ipaffs.PartyTypeEnum.PrivateTransporter => Cdms.Model.Ipaffs.PartyTypeEnum.PrivateTransporter,

            _ => throw new ArgumentOutOfRangeException(nameof(from), from, null)
        };
    }


}


