//------------------------------------------------------------------------------
// <auto-generated>
	//     This code was generated from a template.
	//
	//     Manual changes to this file may cause unexpected behavior in your application.
	//     Manual changes to this file will be overwritten if the code is regenerated.
	//
//</auto-generated>
//------------------------------------------------------------------------------
#nullable enable


namespace Cdms.Types.Ipaffs.Mapping;

public static class PartThreeMapper
{
	public static Cdms.Model.Ipaffs.PartThree Map(Cdms.Types.Ipaffs.PartThree from)
	{
	if(from is null)
	{
		return default!;
	}
		var to = new Cdms.Model.Ipaffs.PartThree ();
to.ControlStatus = PartThreeControlStatusEnumMapper.Map(from?.ControlStatus);
                to.Control = ControlMapper.Map(from?.Control);
                to.ConsignmentValidations = from?.ConsignmentValidations?.Select(x => ValidationMessageCodeMapper.Map(x)).ToArray();
                to.SealCheckRequired = from.SealCheckRequired;
            to.SealCheck = SealCheckMapper.Map(from?.SealCheck);
                to.SealCheckOverride = InspectionOverrideMapper.Map(from?.SealCheckOverride);
                	return to;
	}
}

