//------------------------------------------------------------------------------
// <auto-generated>
    //     This code was generated from a template.
    //
    //     Manual changes to this file may cause unexpected behavior in your application.
    //     Manual changes to this file will be overwritten if the code is regenerated.
    // </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Cdms.Types.Ipaffs.Mapping;

public static class PartThreeControlStatusEnumMapper
{
public static Cdms.Model.Ipaffs.PartThreeControlStatusEnum? Map(Cdms.Types.Ipaffs.PartThreeControlStatusEnum? from)
{
if(from == null)
{
return default!;
}
return from switch
{
Cdms.Types.Ipaffs.PartThreeControlStatusEnum.Required => Cdms.Model.Ipaffs.PartThreeControlStatusEnum.Required,
    Cdms.Types.Ipaffs.PartThreeControlStatusEnum.Completed => Cdms.Model.Ipaffs.PartThreeControlStatusEnum.Completed,
     
};
}
        

}


