//------------------------------------------------------------------------------
// <auto-generated>
	//     This code was generated from a template.
	//
	//     Manual changes to this file may cause unexpected behavior in your application.
	//     Manual changes to this file will be overwritten if the code is regenerated.
	//
//</auto-generated>
//------------------------------------------------------------------------------
#nullable enable


namespace Cdms.Types.Ipaffs.Mapping;

public static class RiskAssessmentResultMapper
{
    public static Cdms.Model.Ipaffs.RiskAssessmentResult Map(Cdms.Types.Ipaffs.RiskAssessmentResult from)
    {
        if (from is null)
        {
            return default!;
        }

        var to = new Cdms.Model.Ipaffs.RiskAssessmentResult();
        to.CommodityResults = from?.CommodityResults?.Select(x => CommodityRiskResultMapper.Map(x)).ToArray();
        to.AssessedOn = from?.AssessmentDateTime;
        return to;
    }
}

