//------------------------------------------------------------------------------
// <auto-generated>
    //     This code was generated from a template.
    //
    //     Manual changes to this file may cause unexpected behavior in your application.
    //     Manual changes to this file will be overwritten if the code is regenerated.
    // </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Cdms.Types.Ipaffs.Mapping;

public static class TemperatureEnumMapper
{
public static Cdms.Model.Ipaffs.TemperatureEnum? Map(Cdms.Types.Ipaffs.TemperatureEnum? from)
{
if(from == null)
{
return default!;
}
return from switch
{
Cdms.Types.Ipaffs.TemperatureEnum.Ambient => Cdms.Model.Ipaffs.TemperatureEnum.Ambient,
    Cdms.Types.Ipaffs.TemperatureEnum.Chilled => Cdms.Model.Ipaffs.TemperatureEnum.Chilled,
    Cdms.Types.Ipaffs.TemperatureEnum.Frozen => Cdms.Model.Ipaffs.TemperatureEnum.Frozen,
     
};
}
        

}


