//------------------------------------------------------------------------------
// <auto-generated>
    //     This code was generated from a template.
    //
    //     Manual changes to this file may cause unexpected behavior in your application.
    //     Manual changes to this file will be overwritten if the code is regenerated.
    // </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Cdms.Types.Ipaffs.Mapping;

public static class UnitEnumMapper
{
    public static Cdms.Model.Ipaffs.UnitEnum? Map(Cdms.Types.Ipaffs.UnitEnum? from)
    {
        if (from == null)
        {
            return default!;
        }

        return from switch
        {
            Cdms.Types.Ipaffs.UnitEnum.Percent => Cdms.Model.Ipaffs.UnitEnum.Percent,
            Cdms.Types.Ipaffs.UnitEnum.Number => Cdms.Model.Ipaffs.UnitEnum.Number,

            _ => throw new ArgumentOutOfRangeException(nameof(from), from, null)
        };
    }


}


