//------------------------------------------------------------------------------
// <auto-generated>
	//     This code was generated from a template.
	//
	//     Manual changes to this file may cause unexpected behavior in your application.
	//     Manual changes to this file will be overwritten if the code is regenerated.
	//
//</auto-generated>
//------------------------------------------------------------------------------
#nullable enable


namespace Cdms.Types.Ipaffs.Mapping;

public static class UserInformationMapper
{
	public static Cdms.Model.Ipaffs.UserInformation Map(Cdms.Types.Ipaffs.UserInformation from)
	{
	if(from is null)
	{
		return default!;
	}
		var to = new Cdms.Model.Ipaffs.UserInformation ();
to.DisplayName = from.DisplayName;
            to.UserId = from.UserId;
            to.IsControlUser = from.IsControlUser;
            	return to;
	}
}

