name: Check Pull Request

on:
  pull_request:
    branches:
      - main
    types:
      - opened
      - edited
      - reopened
      - synchronize
      - ready_for_review

jobs:
  pr-validator:
    name: Run Pull Request Checks
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3      
      - name: Start MongoDB
        uses: supercharge/mongodb-github-action@1.11.0
        with:
          mongodb-version: '7.0'
          mongodb-replica-set: test-rs
      - name: Test
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: |
            8.0
      - run: dotnet test  --logger "GitHubActions;summary.includePassedTests=true;summary.includeSkippedTests=true" --collect:"XPlat Code Coverage" --results-directory ./coverage
  
      - name: Code Coverage Report
        uses: irongut/CodeCoverageSummary@v1.3.0
        with:
          filename: coverage/**/coverage.cobertura.xml
          badge: true
          fail_below_min: false
          format: markdown
          hide_branch_rate: false
          hide_complexity: true
          indicators: true
          output: both
          thresholds: '60 80'

      - name: Add Coverage PR Comment
        uses: marocchino/sticky-pull-request-comment@v2
        if: github.event_name == 'pull_request'
        with:
          recreate: true
          path: code-coverage-results.md
    
    ## SonarCloud
    ## Uncomment to unable SonarCloud scan
    ## Requires project to be set up in SonarCloud
    ## and the SonarCloud token to be set in the repository secrets
#   sonarcloud-scan:
#     name: CDP SonarCloud Scan
#     uses: ./.github/workflows/sonarcloud.yml
#     needs: pr-validator
#     secrets: inherit
